In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
DATA_DIR = Path("../data/raw/samanantar_ml")

files = sorted(DATA_DIR.glob("*.parquet"))

print("Number of files:", len(files))

for file in files:
    print(file.name)

Number of files: 4
train-00000-of-00004.parquet
train-00001-of-00004.parquet
train-00002-of-00004.parquet
train-00003-of-00004.parquet

In [3]:
df = pd.read_parquet(files[0])

print("Rows:", len(df))
print("Columns:", df.columns.tolist())

Rows: 1481107
Columns: ['idx', 'src', 'tgt']

In [4]:
df.head()

,idx,src,tgt
0,0,The plot of the movie revolves around the life...,"ക്യാന്‍സറിനോട് പോരാടുന്ന കിസി, മാനി എന്നിവരുടെ..."
1,1,The same as on the stone.,കല്ലിൽ കണ്ട അതേ രൂപം.
2,2,"Oommen Chandy, Mullappally Ramachandran, Rames...",മാണി നയിക്കുന്ന കേരള യാത്രയിലുടനീളം ഉമ്മന്‍ചാണ...
3,3,Many were arrested and jailed.,നിരപരാധികളായ പലരേയും കസ്റ്റഡിയിലെടുത്ത് പീഢിപ്...
4,4,what has happened?,എന്താണു സംഭവം?

In [5]:
print("Dataset Shape:", df.shape)
print("\nColumn Information:")
print(df.info())

Dataset Shape: (1481107, 3)

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1481107 entries, 0 to 1481106
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   idx     1481107 non-null  int64
 1   src     1481107 non-null  object
 2   tgt     1481107 non-null  object
dtypes: int64(1), object(2)
memory usage: 33.9+ MB
None

In [6]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
idx    0
src    0
tgt    0
dtype: int64

In [7]:
print("\nDuplicate Rows:", df.duplicated().sum())

print("Duplicate English Sentences:", df["src"].duplicated().sum())
print("Duplicate Malayalam Sentences:", df["tgt"].duplicated().sum())

Duplicate Rows: 0
Duplicate English Sentences: 442629
Duplicate Malayalam Sentences: 44865

In [8]:
print("\nDuplicate Rows:", df.duplicated().sum())

print("Duplicate English Sentences:", df["src"].duplicated().sum())
print("Duplicate Malayalam Sentences:", df["tgt"].duplicated().sum())

Duplicate Rows: 0
Duplicate English Sentences: 442629
Duplicate Malayalam Sentences: 44865

In [9]:
for i in range(5):
    print(f"\n--- Example {i+1} ---")
    print("English   :", df.loc[i, "src"])
    print("Malayalam :", df.loc[i, "tgt"])

--- Example 1 ---
English   : The plot of the movie revolves around the life of two cancer patients Kizie and Manny.
Malayalam : ക്യാന്‍സറിനോട് പോരാടുന്ന കിസി, മാനി എന്നിവരുടെ ജീവിതമാണ് ചിത്രം പറയുന്നത്.

--- Example 2 ---
English   : The same as on the stone.
Malayalam : കല്ലിൽ കണ്ട അതേ രൂപം.

--- Example 3 ---
English   : Oommen Chandy, Mullappally Ramachandran, Ramesh Chennithala and P.K.
Malayalam : മാണി നയിക്കുന്ന കേരള യാത്രയിലുടനീളം ഉമ്മന്‍ചാണ്ടി, പി. കെ കുഞ്ഞാലിക്കുട്ടി, മുല്ലപ്പള്ളി രാമചന്ദ്രന്‍, രമേശ് ചെന്നിത്തല, എം.

--- Example 4 ---
English   : Many were arrested and jailed.
Malayalam : നിരപരാധികളായ പലരേയും കസ്റ്റഡിയിലെടുത്ത് പീഢിപ്പിക്കുകയുമാണ്.

--- Example 5 ---
English   : what has happened?
Malayalam : എന്താണു സംഭവം?

In [10]:
print("Rows:", len(df))
print("Columns:", df.columns.tolist())

Rows: 1481107
Columns: ['idx', 'src', 'tgt']

In [11]:
df["src_words"] = df["src"].str.split().str.len()
df["tgt_words"] = df["tgt"].str.split().str.len()

print("English word count:")
print(df["src_words"].describe())

print("\nMalayalam word count:")
print(df["tgt_words"].describe())

English word count:
count    1.481107e+06
mean     1.020258e+01
std      9.083081e+00
min      1.000000e+00
25%      5.000000e+00
50%      8.000000e+00
75%      1.300000e+01
max      3.149000e+03
Name: src_words, dtype: float64

Malayalam word count:
count    1.481107e+06
mean     6.961649e+00
std      5.867122e+00
min      1.000000e+00
25%      4.000000e+00
50%      5.000000e+00
75%      8.000000e+00
max      8.290000e+02
Name: tgt_words, dtype: float64

In [12]:
print("English sentences with 1 word:")
print((df["src_words"] == 1).sum())

print("Malayalam sentences with 1 word:")
print((df["tgt_words"] == 1).sum())

print("English sentences > 100 words:")
print((df["src_words"] > 100).sum())

print("Malayalam sentences > 100 words:")
print((df["tgt_words"] > 100).sum())

English sentences with 1 word:
964
Malayalam sentences with 1 word:
12082
English sentences > 100 words:
446
Malayalam sentences > 100 words:
78

In [13]:
translation_counts = df.groupby("src")["tgt"].nunique()

print("English sentences with multiple Malayalam translations:",
      (translation_counts > 1).sum())

print("\nMaximum different Malayalam translations for one English sentence:",
      translation_counts.max())

English sentences with multiple Malayalam translations: 197366

Maximum different Malayalam translations for one English sentence: 199

In [14]:
repeated_src = df[df["src"].duplicated(keep=False)].sort_values("src")

repeated_src[["src", "tgt"]].head(20)

                             src                            tgt
315254               ! I gasped.                        ഞാനലറി.
878676               ! I gasped.                 ’ ഞാൻ കിതച്ചു.
223371   ! I said with a shiver.      ’’ ഞാൻ നീരസത്തോടെ പറഞ്ഞു.
755617   ! I said with a shiver.         വിറയലോടെ ഞാന്‍ പറഞ്ഞു.
1477456               ! he said.            ' അദ്ദേഹം ഓര്‍ത്തു.
634469                ! he said.                  ’ അയാളോർത്തു.
1312743             ! she asked!          ’ എന്ന് ചോദിക്കുന്നു!
1306779             ! she asked!            """ അവർ ചോദിച്ചു !"
496707              ! she asked!              ’ എന്നു ചോദിച്ചു!
614708              ! she asked!            ’ അവർ ചോദിക്കുന്നു!
1379772  """ 'That's all right."  ''അതൊക്കെ തലൈവര്‍ ശൊല്ലുവാറ്.
530302   """ 'That's all right."                '' ആകെ ബഹളമായി.
1477257         """ Arora says."           ,'' ഹരിഹരൻ പറയുന്നു.
1376429         """ Arora says."               '' സോറ പറയുന്നു.
190052          """ Arora says."        """ അരുണാചലം പറയുന്നു."
1069543         """ Arora says."             ’ ഷാരൂഖ് പറയുന്നു.
1463602         """ Arora says."              ' ശ്രിയ പറയുന്നു.
665733          """ Arora says."           ’ - രജോരിയ പറയുന്നു.
600596          """ Arora says."             '' ഭൂരിയ പറയുന്നു.
782096           """ Khan said."         ’ എന്നും ഖാന്‍ പറഞ്ഞു.

In [15]:
samples = df.sample(20, random_state=42)

for i, row in samples.iterrows():
    print("\n--------------------------------")
    print("EN:", row["src"])
    print("ML:", row["tgt"])

--------------------------------
EN: I'm not taking my eyes off the road.
ML: ഞാൻ റോഡിൽ നിന്ന് കണ്ണുകൾ എടുക്കുന്നേയില്ല.

--------------------------------
EN: Various reforms have been undertaken since independence
ML: സ്വാതന്ത്ര്യലബ്ധിക്കുശേഷം വിവിധ പരിഷ്‌കാരങ്ങള്‍ നടത്തിയിട്ടുണ്ട്.

--------------------------------
EN: Recall the many touching and emotional scenes we read about in the Bible.
ML: ബൈബിളിൽ നാം വായിച്ചിട്ടുള്ള വികാരനിർഭരമായ ചില സന്ദർഭങ്ങളെക്കുറിച്ച് ഓർക്കുക.

--------------------------------
EN: The death toll has risen to 71 there.
ML: ഇതോടെ മരിച്ചവരുടെ എണ്ണം 71 ആയി.

--------------------------------
EN: There might be some problems in the personal relationship.
ML: വ്യക്തിപരമായ ബന്ധങ്ങളില്‍ ചില വിട്ടുവീഴ്ചകള്‍ വേണ്ടി വന്നേക്കാം.

--------------------------------
EN: The protesters who were students have been demanding justice for the victim.
ML: കൊല്ലപ്പെട്ട വിദ്യാര്‍ഥികള്‍ക്ക് നീതി ലഭ്യമാക്കണമെന്ന് പ്രതിഷേധക്കാര്‍ ആവശ്യപ്പെട്ടു.

--------------------------------
EN: The 80 - year - old man who said this to Israels King David was Barzillai.
ML: ഇസ്രായേൽ രാജാവായ ദാവീദിനോട്‌ ഇങ്ങനെ പറഞ്ഞത്‌ 80 വയസ്സുള്ള ബർസില്ലായി ആയിരുന്നു.

--------------------------------
EN: Doctor killed in accident
ML: വാഹനാപകടത്തില്‍ ഡോക്ടര്‍ക്ക് പരിക്ക്‌

--------------------------------
EN: A video was posted by news agency ANI.
ML: വാര്‍ത്താ ഏജന്‍സിയായ എ. എന്‍. ഐ ആണ് വിഡിയോ പുറത്തുവിട്ടത്.

--------------------------------
EN: Since then, a simplified edition has been made available in a few additional languages.
ML: പിന്നീട്‌ പല ഭാഷക ​ ളി ​ ലും ഈ പതിപ്പ് പ്രസി ​ ദ്ധീ ​ ക ​ രി ​ ക്കാൻ തുടങ്ങി.

--------------------------------
EN: All kinds of tests will be conducted.
ML: എല്ലാവിധ പരിശോധനകളും നടത്തും.

--------------------------------
EN: She filed a complaint to the police in this regard.
ML: ഇതിനെതിരെ സ്ഥാനാർത്ഥി പൊലീസിൽ പരാതി നൽകിയിരുന്നു.

--------------------------------
EN: Two months ago he took her for a drive with another boyfriend.
ML: രണ്ടു മാസം മുന്‍പ്‌ അവര്‍ രണ്ടുപേരും കൂടെ വേറൊരുവനുമൊത്ത് ഒന്ന് ചുറ്റാന്‍ പോയി.

--------------------------------
EN: India had said it had nothing to do with the assault.
ML: ആക്രമണവുമായി യാതൊരു ബന്ധവുമില്ലെന്ന് ഇന്ത്യ വ്യക്​തമാക്കിയിരുന്നു

--------------------------------
EN: Cancer in India:
ML: ഇന്ത്യയിൽ കാൻസർ രോഗത്തിനു ലഭിക്കുന്ന .

--------------------------------
EN: School figures See compulsory figures.
ML: അദ്ധ്യായങ്ങൾ പ്രപാഠകങ്ങൾ എന്നറിയപ്പെടുന്നു.

--------------------------------
EN: Plastic bags under 50 microns are banned.
ML: 50 മൈക്രോണിൽ താഴെയുള്ള പ്ലാസ്റ്റിക് ക്യാരിബാഗുകൾക്കാണ് നിരോധനം.

--------------------------------
EN: The front and the tail supposed to work together.
ML: തലയും വാലും ഒന്നിച്ചാണ് പ്രവർത്തിക്കേണ്ടത്.

--------------------------------
EN: How did the family react?
ML: കുടുംബം എങ്ങനെയാണ് പ്രതികരിച്ചത്

--------------------------------
EN: Indian team would be sporting orange jersey against England.
ML: പുതിയ ഓറഞ്ച് ജെഴ്‌സിയിലാണ് ടീം ഇന്ത്യ ഇംഗ്ലണ്ടിനെ നേരിടുന്നത്.

In [16]:
import re

def malayalam_char_ratio(text):
    if not isinstance(text, str) or len(text) == 0:
        return 0
    
    mal_chars = re.findall(r'[\u0D00-\u0D7F]', text)
    letters = re.findall(r'[^\W\d_]', text, flags=re.UNICODE)
    
    if len(letters) == 0:
        return 0
    
    return len(mal_chars) / len(letters)


df["ml_script_ratio"] = df["tgt"].apply(malayalam_char_ratio)

print(df["ml_script_ratio"].describe())

count    1.481107e+06
mean     1.719067e+00
std      1.230977e-01
min      1.837838e-01
25%      1.661765e+00
50%      1.725490e+00
75%      1.787879e+00
max      4.000000e+00
Name: ml_script_ratio, dtype: float64

In [17]:
print("Pairs with no Malayalam script:",
      (df["ml_script_ratio"] == 0).sum())

print("Pairs with less than 50% Malayalam script:",
      (df["ml_script_ratio"] < 0.5).sum())

print("Pairs with more than 90% Malayalam script:",
      (df["ml_script_ratio"] > 0.9).sum())

Pairs with no Malayalam script: 0
Pairs with less than 50% Malayalam script: 660
Pairs with more than 90% Malayalam script: 1478048

In [18]:
df["length_ratio"] = (
    df["tgt_words"] / df["src_words"]
)

print(df["length_ratio"].describe())

count    1.481107e+06
mean     7.603162e-01
std      3.634575e-01
min      1.183432e-02
25%      5.625000e-01
50%      7.000000e-01
75%      9.000000e-01
max      1.658000e+02
Name: length_ratio, dtype: float64

In [19]:
print("Very short Malayalam relative to English:",
      (df["length_ratio"] < 0.2).sum())

print("Very long Malayalam relative to English:",
      (df["length_ratio"] > 3).sum())

Very short Malayalam relative to English: 5757
Very long Malayalam relative to English: 1678

In [20]:
suspicious = df[
    (df["ml_script_ratio"] < 0.5)
].copy()

print("Suspicious pairs:", len(suspicious))

for i, row in suspicious.head(20).iterrows():
    print("\n-------------------------")
    print("EN:", row["src"])
    print("ML:", row["tgt"])

Suspicious pairs: 660

-------------------------
EN: Redwood City
ML: സെഡാര്‍ സിറ്റിCity in California USA

-------------------------
EN: In R.R. Wise. J.K. Hoober.
ML: എന്നതിൽ R.R. Wise. J.K. Hoober.

-------------------------
EN: No power in the world can ever seperate Kashmir from India.
ML: ലോകത്തില്‍ ഒരു ശക്തിക്കും കശ്മീരിനെ ഇന്ത്യയില്‍ നിന്നും കവരാനാകില്ല,no one can take Kashmir from India says rajnath singhkeralaonlinenews.com | Malayalam news, kerala news, onlinenews,

-------------------------
EN: """Mohammed renames Emirates Road after Sheikh Mohammed bin Zayed""."
ML: "വിക്കിവൊയേജിൽ നിന്നുള്ള Emirates Road യാത്രാ സഹായി ""Mohammed renames Emirates Road after Sheikh Mohammed bin Zayed""."

-------------------------
EN: Third quarter
ML: മൂന്നാം കാല്‍ഭാഗംmoon phase between new moon and 1st quarter

-------------------------
EN: Intervene more aggressively to soften Rupee drop, government tells RBI: Report
ML: രൂപയുടെ വീഴ്ച തടയാന്‍ ശക്തമായി ഇടപെടണം. ആര്‍ബിഐക്ക് സര്‍ക്കാര്‍ നിര്‍ദ്ദേശം,intervene more aggressively to soften rupee drop government tells rbikeralaonlinenews.com | Malayalam news, kerala news, onlinenews,

-------------------------
EN: RRB Group D exam 2018: Re-obtain your registration ID, admit card released
ML: RRB Group D Admit Card: rrb group d exam 2018 admit card released: download link here - RRB Group D: ആർആർബി ഗ്രൂപ്പ് ഡി പരീക്ഷ: ഹാൾ ടിക്കറ്റ് വിതരണം ആരംഭിച്ചു | Samayam Malayalam

-------------------------
EN: Olympic champion Germain Mason dies in bike accident
ML: British Olympic silver medallist Germaine Mason: british olympic silver medallist germaine mason killed - ഒ​ളി​മ്പി​ക് വെ​ള്ളി​മെ​ഡ​ൽ ജേ​താ​വ് ബൈ​ക്ക് അ​പ​ക​ട​ത്തി​ൽ മ​രി​ച്ചു | Samayam Malayalam

-------------------------
EN: EXPONDIST(3. 0.5. 0) equals 0.111565
ML: EXPONDIST( 3. 0. 5. 0) സമം 0. 111565

-------------------------
EN: Principal of Delhi school arrested in CBSE paper leak case
ML: cbse paper leak: school principal arrested in delhi cbse paper leak case - സിബിഎസ്‌ഇ ചോദ്യപേപ്പര്‍ ചോര്‍ച്ച: പ്രിന്‍സിപ്പല്‍ അറസ്റ്റില്‍ | Samayam Malayalam

-------------------------
EN: Official website Official website (open access version, starting 2012) Journals of semiotics in the world
ML: ഔദ്യോഗിക വെബ്സൈറ്റ് ഔദ്യോഗിക വെബ്സൈറ്റ് (open access version, starting 2012) Journals of semiotics in the world

-------------------------
EN: Your names
ML: ശങ്കരനാരായണന്‍EMAIL OF TRANSLATORS

-------------------------
EN: Fire the ball
ML: പന്തുതിര്‍ക്കുകKey (shortcut) to pause the game

-------------------------
EN: HDFC Life, ICICI Prudential Life and SBI Life in focus.
ML: Bajaj Finserv  2.8%, Bajaj Finance 1.4%, SBI Life 2.5%, HDFC Life 2% നേട്ടം കെെവരിച്ചു.

-------------------------
EN: Mowgli Legend of the Jungle trailer: Benedict Cumberbatch voices Shere Khan in Andy Serkis' adaptation
ML: ﻿ Mowgli Legend of the Jungle trailer: Benedict Cumberbatch voices Shere Khan in Andy Serkis’ adaptation: കാടിന്റെ വിശേഷങ്ങളുമായി മൗഗ്ലി വീണ്ടുമെത്തുന്നു. ട്രെയിലർ കാണാം

-------------------------
EN: mint-india-wire Sabarimala temple Sabarimala temple women entry BJP protests against women entry Supreme Court Sabarimala verdict Shiv Sena Ayyappa temple RSS Pinarayi Vijayan
ML: bjp cpm sabarimala sabarimala temple ayyappan supreme court verdict women entry ബിജെപി സിപിഎം ശബരിമല സ്ത്രീപ്രവേശനം സന്നിധാനം സുപ്രീം കോടതി വിധി sridharan pillai president p s sreedharan pillai

-------------------------
EN: In breeding & non-breeding plumage near Hodal in Faridabad District of Haryana, India.
ML: പ്രജനന സമയമല്ലാത്തപ്പോൾ, പൂർബസ്ഥലിയിൽ, പ. ബംഗാൾ. In Breeding & Non-breeding plumage near Hodal in Faridabad District of Haryana, India.

-------------------------
EN: COILED THONG
ML: കോയില്‍‌ഡ് തോങ്ങ് (Coiled Thong) Constellation name (optional)

-------------------------
EN: The plant genera Mezia (Schwacke ex Nied.)
ML: സസ്യജനുസുകളായ Mezia (Schwacke ex Nied.

-------------------------
EN: This is not a KDE Vocabulary document.
ML: ഇതൊരു കെ ഡി ഇ പദാവലി രേഖയല്ല. A generic name for a new lesson and its number.

In [21]:
extreme = df[
    (df["src_words"] > 100) |
    (df["tgt_words"] > 100)
]

print("Extreme-length pairs:", len(extreme))

Extreme-length pairs: 498

In [22]:
for i, row in extreme.head(10).iterrows():
    print("\n-------------------------")
    print("English words:", row["src_words"])
    print("Malayalam words:", row["tgt_words"])
    print("EN:", row["src"][:500])
    print("ML:", row["tgt"][:500])

-------------------------
English words: 111
Malayalam words: 68
EN: "When Talut set forth with the armies, he said: ""Allah will test you at the stream: if any drinks of its water, He goes not with my army: Only those who taste not of it go with me: A mere sip out of the hand is excused."" but they all drank of it, except a few. When they crossed the river,- He and the faithful ones with him,- they said: ""This day We cannot cope with Goliath and his forces."" but those who were convinced that they must meet Allah, said: ""How oft, by Allah's will, Hath a small
ML: "അങ്ങനെ പട്ടാളവുമായി ത്വാലൂത്ത് പുറപ്പെട്ടപ്പോള്‍ ‎പറഞ്ഞു: “അല്ലാഹു ഒരു നദികൊണ്ട് നിങ്ങളെ ‎പരീക്ഷിക്കാന്‍ പോവുകയാണ്. അതില്‍നിന്ന് ‎കുടിക്കുന്നവനാരോ, അവന്‍ എന്റെ കൂട്ടത്തില്‍ ‎പെട്ടവനല്ല. അത് രുചിച്ചുനോക്കാത്തവനാരോ അവനാണ് ‎എന്റെ അനുയായി. എന്നാല്‍ തന്റെ കൈകൊണ്ട് ഒരു ‎കോരല്‍ എടുത്തവന്‍ ഇതില്‍ നിന്നൊഴിവാണ്."" പക്ഷേ, ‎അവരില്‍ ചുരുക്കം ചിലരൊഴികെ എല്ലാവരും ‎അതില്‍നിന്ന് ഇഷ്ടംപോലെ കുടിച്ചു. അങ്ങനെ ‎ത്വാലൂത്തും കൂടെയുള്ള വിശ്വാസികളും ആ നദി ‎മുറിച്ചുകടന്നു മുന്നോട്ടുപോയപ്പോള്‍ അവര്‍ പറഞ്ഞു: ‎‎“ജാലൂത്തിനെയ

-------------------------
English words: 106
Malayalam words: 62
EN: "And when Musa (Moses) returned to his people, angry and grieved, he said: ""What an evil thing is that which you have done (i.e. worshipping the calf) during my absence. Did you hasten and go ahead as regards the matter of your Lord (you left His worship)?"" And he threw down the Tablets and seized his brother by (the hair of) his head and dragged him towards him. Harun (Aaron) said: ""O son of my mother! Indeed the people judged me weak and were about to kill me, so make not the enemies rejoic
ML: കുപിതനും ദുഃഖിതനുമായിക്കൊണ്ട് തന്‍റെ ജനങ്ങളിലേക്ക് മടങ്ങി വന്നിട്ട് മൂസാ പറഞ്ഞു: ഞാന്‍ പോയ ശേഷം എന്‍റെ പിന്നില്‍ നിങ്ങള്‍ പ്രവര്‍ത്തിച്ച കാര്യം വളരെ ചീത്ത തന്നെ. നിങ്ങളുടെ രക്ഷിതാവിന്‍റെ കല്‍പന കാത്തിരിക്കാതെ നിങ്ങള്‍ ധൃതികൂട്ടിയോ? അദ്ദേഹം പലകകള്‍ താഴെയിടുകയും, തന്‍റെ സഹോദരന്‍റെ തല പിടിച്ച് തന്‍റെ അടുത്തേക്ക് വലിക്കുകയും ചെയ്തു. അവന്‍ (സഹോദരന്‍) പറഞ്ഞു: എന്‍റെ ഉമ്മയുടെ മകനേ, ജനങ്ങള്‍ എന്നെ ദുര്‍ബലനായി ഗണിച്ചു. അവരെന്നെ കൊന്നേക്കുമായിരുന്നു. അതിനാല്‍ (എന്നോട് കയര്‍ത്തു കൊണ്ട്‌) നീ ശത്രുക്കള്‍ക്ക്

-------------------------
English words: 25
Malayalam words: 140
EN: Akshay Kumar won the National Film Awards for Best Actor for Rustom and Malayalam star Surabhi Lakshmi was awarded Best Actress for Minnaminungu The Firefly
ML: ദേശീയ ചലച്ചിത്ര പുരസ്‌കാരത്തില്‍ മലയാള ചിത്രങ്ങള്‍ക്ക്‌ മികച്ച നേട്ടം. മിന്നാമിനുങ്ങ്‌ എന്ന മലയാള ചലച്ചിത്രത്തിലെ അഭിനയത്തിന്‌ സുരഭിക്കാണ്‌ മികച്ച നടിക്കുള്ള പുരസ്‌കാരം. റുസ്‌തം എന്ന ചിത്രത്തിലെ മികച്ച പ്രകടനത്തിന്‌ അക്ഷയ്‌ കുമാറിനെ മികച്ച നടനായി തിരഞ്ഞെടുത്തു. നവാഗതനായ ദിലീഷ്‌ പോത്തന്‍ സംവിധാനം ചെയ്‌ത മഹേഷിന്റെ പ്രതികാരം മികച്ച മലയാള ചലച്ചിത്ത്രിതനുള്ള പുരസ്‌കാരം സ്വന്തമാക്കി. പുലിമുരുകന്‍, മുന്തിരിവള്ളികള്‍ തളിര്‍ക്കുമ്പോള്‍, തെലുങ്കുചിത്രം ജനതാ ഗാരേജ്‌ എന്നീ ചിത്രത്തിലെ അഭിനയത്തിന്‌ മോഹന്‍ലാല

-------------------------
English words: 111
Malayalam words: 89
EN: State Registered Farmer Farmers Benefited 1 ANDHRA PRADESH 1425025 1123085 2 CHANDIGARH 7106 6801 3 CHHATTISGARH 134715 122678 4 GUJARAT 864970 432457 5 HARYANA 2716608 1765449 6 HIMACHAL PRADESH 118248 96747 7 JHARKHAND 77171 2142 8 MADHYA PRADESH 3009991 1080704 9 MAHARASHTRA 1134993 281022 10 ODISHA 52597 9949 11 PUDUCHERRY 10580 11482 12 PUNJAB 210423 125270 13 RAJASTHAN 1305896 595625 14 TAMIL NADU 201311 86510 15 TELANGANA 1815595 1537989 16 UTTAR PRADESH 3296625 722980 17 UTTARAKHAND 4752
ML: സംസ്ഥാനം രജിസ്റ്റര്‍ചെയ്ത കര്‍ഷകര്‍ പ്രയോജനം ലഭിച്ച കര്‍ഷകര്‍ 1 ആന്ധ്രാ പ്രദേശ് 1425025 1123085 2 ചണ്ഡീഗ് 7106 6801 3 ഛത്തീസ്ഗ് 134715 122678 4 ഗുജറാത്ത് 864970 432457 5 ഹരിയാന 2716608 1765449 6 ഹിമാചല്‍ പ്രദേശ് 118248 96747 7 ജാര്‍ഖണ്ഡ് 77171 2142 8 മധ്യ പ്രദേശ് 3009991 1080704 9 മഹാരാഷ്ട്ര 1134993 281022 10 ഒഡീഷ 52597 9949 11 പുതുച്ചേരി 10580 11482 12 പഞ്ചാബ് 210423 125270 13 രാജസ്ഥാന്‍ 1305896 595625 14 തമിഴ്‌നാട് 201311 86510 15 തെലങ്കാന 1815595 1537989 16 ഉത്തര്‍ പ്രദേശ് 3296625 722980 17 ഉ

-------------------------
English words: 150
Malayalam words: 74
EN: And complete the Hajj and 'umrah for Allah. But if you are prevented, then [offer] what can be obtained with ease of sacrificial animals. And do not shave your heads until the sacrificial animal has reached its place of slaughter. And whoever among you is ill or has an ailment of the head [making shaving necessary must offer] a ransom of fasting [three days] or charity or sacrifice. And when you are secure, then whoever performs 'umrah [during the Hajj months] followed by Hajj [offers] what can
ML: നിങ്ങള്‍ അല്ലാഹുവിനായി ഹജ്ജും ഉംറയും തികവോടെ ‎നിര്‍വഹിക്കുക. അഥവാ, നിങ്ങള്‍ ഉപരോധിക്കപ്പെട്ടാ ല്‍ ‎നിങ്ങള്‍ക്ക് സാധ്യമായ രീതിയില്‍ ബലിനടത്തുക. ‎ബലിമൃഗം അതിന്റെ സ്ഥാനത്ത് എത്തുവോളം നിങ്ങള്‍ ‎തലമുടിയെടുക്കരുത്. അഥവാ, ആരെങ്കിലും രോഗം ‎കാരണമോ തലയിലെ മറ്റെന്തെങ്കിലും പ്രയാസം മൂലമോ ‎മുടി എടുത്താല്‍ പ്രായശ്ചിത്തമായി നോമ്പെടുക്കുകയോ ‎ദാനം നല്‍കുകയോ ബലിനടത്തുകയോ വേണം. നിങ്ങള്‍ ‎നിര്‍ഭയാവസ്ഥയിലാവുകയും ഉംറ നിര്‍വഹിച്ച് ഹജ്ജ് ‎കാലംവരെ സൌകര്യം ഉപയോഗപ്പെടുത്തുക ‎യുമാണെങ്കില്‍ സാധ്യമായ ബലി നല്‍കുക. ‎ആര്‍ക്കെങ്

-------------------------
English words: 106
Malayalam words: 53
EN: O ye who believe! when ye stand up for the prayer wash your faces and your hands unto the elbows, and wipe your heads, and wash your feet unto the ankles. And if ye be polluted, then purify yourselves And if ye be ailing or on a journey or one of you cometh from the privy or ye have touched women, and ye find not water, then betake yourselves to clean earth and wipe your faces and hands therewith. Allah intendeth not to lay upon you a hardship, but intendeth to purify you and to complete His fav
ML: വിശ്വസിച്ചവരേ, നിങ്ങള്‍ നമസ്കാരത്തിനൊരുങ്ങിയാല്‍ നിങ്ങളുടെ മുഖങ്ങളും മുട്ടുവരെ ഇരുകരങ്ങളും കഴുകുക. തല തടവുകയും ഞെരിയാണിവരെ കാലുകള്‍ കഴുകുകയും ചെയ്യുക. നിങ്ങള്‍ വലിയ അശുദ്ധിയുള്ളവരാണെങ്കില്‍ കുളിച്ചു ശുദ്ധിയാവുക. രോഗികളോ യാത്രക്കാരോ ആണെങ്കിലും നിങ്ങളിലാരെങ്കിലും വിസര്‍ജിച്ചുവരികയോ സ്ത്രീസംസര്‍ഗം നടത്തുകയോ ചെയ്തിട്ട് വെള്ളം കിട്ടാതിരിക്കുകയാണെങ്കിലും ശുദ്ധിവരുത്താന്‍ മാലിന്യമില്ലാത്ത മണ്ണ് ഉപയോഗിക്കുക. അതില്‍ കയ്യടിച്ച് മുഖവും കൈകളും തടവുക. നിങ്ങളെ പ്രയാസപ്പെടുത്താന്‍ അല്ലാഹു ഉദ്ദേശിക്കുന്നില്ല. എ

-------------------------
English words: 106
Malayalam words: 54
EN: "And when Musa (Moses) returned to his people, angry and grieved, he said: ""What an evil thing is that which you have done (i.e. worshipping the calf) during my absence. Did you hasten and go ahead as regards the matter of your Lord (you left His worship)?"" And he threw down the Tablets and seized his brother by (the hair of) his head and dragged him towards him. Harun (Aaron) said: ""O son of my mother! Indeed the people judged me weak and were about to kill me, so make not the enemies rejoic
ML: "മൂസാ കുപിതനും ദുഃഖിതനുമായി തന്റെ ജനതയിലേക്ക് തിരിച്ചുവന്നു. അദ്ദേഹം പറഞ്ഞു: ""എനിക്ക് പിറകെ എന്റെ പ്രതിനിധികളായി നിങ്ങള്‍ ചെയ്തതെല്ലാം വളരെ ചീത്ത തന്നെ. നിങ്ങളുടെ നാഥന്റെ വിധി വരാന്‍ കാത്തിരിക്കാതെ നിങ്ങള്‍ ധൃതി കാണിച്ചോ?” അദ്ദേഹം ഫലകം നിലത്തെറിഞ്ഞു. സഹോദരന്റെ തല തന്റെ നേരെ പിടിച്ചുവലിച്ചു. സഹോദരന്‍ പറഞ്ഞു: ""എന്റെ മാതാവിന്റെ മകനേ, ഈ ജനം എന്നെ കഴിവുകെട്ടവനായിക്കണ്ടു. അവരെന്നെ കൊല്ലുമെന്നേടത്തോളമെത്തി. അതിനാല്‍ എതിരാളികള്‍ക്ക് എന്നെ നോക്കിച്ചിരിക്കാന്‍ ഇടവരുത്താതിരിക്കുക. അക്രമികളായ ജനത്തിന്റെ ക

-------------------------
English words: 131
Malayalam words: 46
EN: I am happy that the people of Indian origin who live in different countries continue to serve those countries and at the same time they have maintained their strong relationship with India as well This time, the European Union, has sent me a calendar, in which they have displayed the contributions by Indians in various fields of life living in different countries of Europe whether working in the field of cyber security, or dedicated to Ayurveda, entertaining the society through music, or through
ML: അതില്‍ അവര്‍ വിവിധ രാജ്യങ്ങളില്‍ താമസിക്കു ഭാരതീയര്‍ വിവിധ മേഖലകളില്‍ നല്‍കിയ സംഭാവനകള്‍ നായി കാണിച്ചിരിക്കുു. നമ്മുടെ ഭാരതവംശജരായ ആളുകള്‍ യൂറോപ്പിലെ വിവിധ രാജ്യങ്ങളില്‍ താമസിക്കുു- ചിലര്‍ സൈബര്‍ സെക്യൂരിറ്റിയുമായി ബന്ധപ്പെ' ജോലി ചെയ്യുു, ചിലര്‍ ആയുര്‍വ്വേദത്തിനായി സമര്‍പ്പിച്ചിരിക്കുു, ചിലര്‍ തങ്ങളുടെ സംഗീതത്തിലൂടെ ചിലര്‍ കവിതകളിലൂടെ സമൂഹത്തിന്റെ മനസ്സിന് താളമേകുു. ചിലര്‍ കാലാവസ്ഥാ വ്യതിയാനതത്തെക്കുറിച്ച് ഗവേഷണം നടത്തുു, ചിലര്‍ ഭാരതീയ ഗ്രന്ഥങ്ങളുമായി ബന്ധപ്പെ' പ്രവര്‍ത്തനങ്ങളിലേര്‍പ്പെ'ിരിക്കുു

-------------------------
English words: 106
Malayalam words: 62
EN: "Undoubtedly Allah made a covenant with the Descendants of Israel, and We appointed twelve chiefs among them. and Allah said, Indeed I am with you. surely, if you establish the prayer and pay the charity, and believe in My Noble Messengers and respect* them, and lend an excellent loan to Allah, I will surely forgive your sins, and I will surely admit you into Gardens beneath which rivers flow. then after this, if any of you disbelieves, he has certainly gone astray from the Straight Path."" (To
ML: അല്ലാഹു ഇസ്രായീല്‍ സന്തതികളോട് കരാര്‍ വാങ്ങുകയും, അവരില്‍ നിന്ന് പന്ത്രണ്ട് നേതാക്കന്‍മാരെ നിയോഗിക്കുകയുമുണ്ടായി. അല്ലാഹു (അവരോട്‌) പറഞ്ഞു: തീര്‍ച്ചയായും ഞാന്‍ നിങ്ങളുടെ കൂടെയുണ്ട്‌. നിങ്ങള്‍ പ്രാര്‍ത്ഥന മുറപോലെ നിര്‍വഹിക്കുകയും, സകാത്ത് നല്‍കുകയും, എന്‍റെ ദൂതന്‍മാരില്‍ വിശ്വസിക്കുകയും, അവരെ സഹായിക്കുകയും, അല്ലാഹുവിന്ന് ഉത്തമമായ കടം കൊടുക്കുകയും ചെയ്തു കൊണ്ടിരിക്കുന്ന പക്ഷം തീര്‍ച്ചയായും നിങ്ങളുടെ തിന്‍മകള്‍ നിങ്ങളില്‍ നിന്ന് ഞാന്‍ മായ്ച്ചുകളയുകയും, താഴ്ഭാഗത്ത് കൂടി അരുവികള്‍ ഒഴുകുന്ന സ്വര്‍ഗത്ത

-------------------------
English words: 101
Malayalam words: 61
EN: "The Jews have said, ""God's hands are bound."" May they themselves be handcuffed and condemned for what they have said! God's hands are free and He distributes His favors to His creatures however He wants. The rebellion and disbelief of many of them will be intensified against you because of what has been revealed to you from your Lord. We have induced hostility and hatred among them which will remain with them up until the Day of Judgment. Whenever they kindle the fire of war, God extinguishes
ML: അല്ലാഹുവിന്‍റെ കൈകള്‍ ബന്ധിക്കപ്പെട്ടിരിക്കുകയാണ് എന്ന് യഹൂദന്‍മാര്‍ പറഞ്ഞു അവരുടെ കൈകള്‍ ബന്ധിതമാകട്ടെ. അവര്‍ പറഞ്ഞ വാക്ക് കാരണം അവര്‍ ശപിക്കപ്പെട്ടിരിക്കുന്നു. അല്ല, അവന്‍റെ ഇരു കൈകളും നിവര്‍ത്തപ്പെട്ടവയാകുന്നു. അവന്‍ എങ്ങനെ ഉദ്ദേശിക്കുന്നുവോ അങ്ങനെ ചെലവഴിക്കുന്നു. നിനക്ക് നിന്‍റെ രക്ഷിതാവിങ്കല്‍ നിന്ന് അവതരിപ്പിക്കപ്പെട്ട സന്ദേശം അവരില്‍ അധികം പേര്‍ക്കും ധിക്കാരവും അവിശ്വാസവും വര്‍ദ്ധിപ്പിക്കുക തന്നെ ചെയ്യും. അവര്‍ക്കിടയില്‍ ഉയിര്‍ത്തെഴുന്നേല്‍പിന്‍റെ നാളുവരെ ശത്രുതയും വിദ്വേഷവും നാം ഇട്ടുകൊട

In [23]:
import re

def script_stats(text):
    if not isinstance(text, str) or not text.strip():
        return pd.Series([0, 0, 0])

    malayalam = len(re.findall(r'[\u0D00-\u0D7F]', text))
    latin = len(re.findall(r'[A-Za-z]', text))
    digits = len(re.findall(r'\d', text))

    return pd.Series([malayalam, latin, digits])


df[["malayalam_chars", "latin_chars", "digit_chars"]] = (
    df["tgt"].apply(script_stats)
)

In [24]:
df["total_relevant_chars"] = (
    df["malayalam_chars"] +
    df["latin_chars"]
)

df["latin_ratio"] = (
    df["latin_chars"] /
    df["total_relevant_chars"].replace(0, np.nan)
)

print(df["latin_ratio"].describe())

count    1.481107e+06
mean     2.227061e-03
std      2.707039e-02
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      8.308458e-01
Name: latin_ratio, dtype: float64

In [25]:
print(
    "Pairs with >20% Latin characters:",
    (df["latin_ratio"] > 0.20).sum()
)

print(
    "Pairs with >50% Latin characters:",
    (df["latin_ratio"] > 0.50).sum()
)

Pairs with >20% Latin characters: 5560
Pairs with >50% Latin characters: 1339

In [26]:
html_pattern = r"<[^>]+>|https?://|www\.|\.com\b|\.in\b"

df["possible_web_noise"] = df["tgt"].str.contains(
    html_pattern,
    regex=True,
    case=False,
    na=False
)

print(
    "Possible web-noise pairs:",
    df["possible_web_noise"].sum()
)

Possible web-noise pairs: 354

In [27]:
web_noise = df[df["possible_web_noise"]]

for _, row in web_noise.head(20).iterrows():
    print("\n-------------------------")
    print("EN:", row["src"])
    print("ML:", row["tgt"])

-------------------------
EN: Water level in Idukki dam rises, reservoir level at highest
ML: ഇടുക്കി ഡാമിൽ ജലനിരപ്പ് ഉയരുന്നു. ചെറുതോണി, മാട്ടുപ്പെട്ടി ഡാമിൽ നിന്നും കൂടുതൽ വെള്ളം തുറന്നുവിടും | Twentyfournews.com

-------------------------
EN: No power in the world can ever seperate Kashmir from India.
ML: ലോകത്തില്‍ ഒരു ശക്തിക്കും കശ്മീരിനെ ഇന്ത്യയില്‍ നിന്നും കവരാനാകില്ല,no one can take Kashmir from India says rajnath singhkeralaonlinenews.com | Malayalam news, kerala news, onlinenews,

-------------------------
EN: Intervene more aggressively to soften Rupee drop, government tells RBI: Report
ML: രൂപയുടെ വീഴ്ച തടയാന്‍ ശക്തമായി ഇടപെടണം. ആര്‍ബിഐക്ക് സര്‍ക്കാര്‍ നിര്‍ദ്ദേശം,intervene more aggressively to soften rupee drop government tells rbikeralaonlinenews.com | Malayalam news, kerala news, onlinenews,

-------------------------
EN: Additionally, India has demonstrated how it rises up to challenges and uncovers opportunities therein, as manifested in the re-purposing of various automobile sector industries to collaborate in the making of life-saving ventilators.
ML: അതിനു പുറമേ, ഇന്ത്യ എങ്ങനെ വെല്ലുവിളികളില്‍ നിന്ന് ഉയര്‍ത്തെഴുന്നേല്‍ക്കുന്നുവെന്നും അവസരങ്ങള്‍ അനാവരണം ചെയ്യുന്നുവെന്നതും വിവിധ ഓട്ടോമൊബൈല്‍ വ്യവസായങ്ങളെ ജീവന്‍രക്ഷാ വെന്റിലേറ്ററുകള്‍ നിര്‍മ്മിക്കുന്നതിനായി പുനര്‍ക്രമീകരിക്കുവാൻ നടത്തിയഇടപെടലുകളിൽ നിന്നും വ്യക്തമാണ്.എന്തെങ്കിലും സംശയങ്ങളുണ്ടെങ്കില്‍ ദയവായി connectmygov.nic.in ബന്ധപ്പെടുക.

-------------------------
EN: Flux 1.0 Copyright (c) 2002 Terence M. Welsh http: / /www. reallyslick. com/ Ported to KDE by Karl Robillard
ML: ഫ്ലക്സ് 1. 0 പകര്‍പ്പവകാശം (c) 2002 ടെറെന്‍സ് എം. വെല്‍ഷ് http: // www. reallyslick. com / കെഡിഇ- യിലേക്കാക്കിയത് കാള്‍ റോബില്ലാഡ്

-------------------------
EN: Application: Application form can be downloaded from https://bcdd.kerala.gov.in .
ML: അപേക്ഷിക്കേണ്ട വിധം: www.prd.kerala.gov.in, www.keralartc.com/html/employzone.html എന്നീ വെബ്സൈറ്റുകളില്‍നിന്ന് ഡൌണ്‍ലോഡ് ചെയ്യാം.

-------------------------
EN: List of helpline numbers of States/UTs on COVID-19 is also available at https://www.mohfw.gov.in/pdf/coronvavirushelplinenumber.pdf.
ML: സംസ്ഥാന -കേന്ദ്രഭരണ പ്രദേശങ്ങളിലെ കോവിഡ് -19  ഹെൽപ്പ്ലൈൻ നമ്പറുകളുടെ പട്ടിക https://www. mohfw. gov. in/pdf/coronvavirushelplinenumber. pdf - ൽ ലഭ്യമാണ്.

-------------------------
EN: The webinar will be held from 11AM to 12 noon every day, and can be viewed on Facebook at https://www.facebook.com/punenin
ML: എല്ലാ ദിവസവും രാവിലെ 11 മുതല്‍ 12 വരെയാണ് വെബിനാര്‍ നടക്കുക. https://www. facebook. com/punenin എന്ന  ഫേസ്ബുക്ക് പേജില്‍ വെബിനാര്‍ കാണാനാകും.

-------------------------
EN: Tickets can be purchased on www.bookmyshow.com .
ML: www.bookmyshow.comല്‍ നിന്നും ഓണ്‍ലൈനായി ടിക്കറ്റുകള്‍ ബുക്ക് ചെയ്യാവുന്നതാണ്. സ്‌റ്റേഡിയം ബോക്‌സ് ഓഫീസില്‍ നിന്നും ഓണ്‍ലൈന്‍ ടിക്കറ്റുകള്‍ മാറ്റിയെടുക്കേണ്ടതാണ്.

-------------------------
EN: Gujarat:With 398 new cases and 30 deaths reported, the total number of Covid-19 cases in the state has risen to 12,539.
ML: കോവിഡ് -19 മായി ബന്ധപ്പെട്ട സാങ്കേതിക അന്വേഷണങ്ങള്‍ക്ക് technicaluery.covid19gov.in എന്ന ഇ മെയിലില്‍ ബന്ധപ്പെടുക.

-------------------------
EN: The result is also available on the UPSC Website at http:// www.upsc.gov.in
ML: പരീക്ഷാഫലംhttp://www. upsc. gov. in എന്ന വെബ്‌സൈറ്റില്‍ ലഭ്യമാണ്.

-------------------------
EN: The two leaders discussed the global challenge posed by the COVID-19 pandemic.
ML: കോവിഡ് 19 മഹാമാരി ഉയര്‍ത്തുന്ന ആഗോള വെല്ലുവിളിയെ കുറിച്ച് ഇരു നേതാക്കളും ചര്‍ച്ച ചെയ്തു. https://pib. gov. in/PressReleseDetail. aspx?

-------------------------
EN: For more information visit: www.
ML: പി. വൈ. എഫ്. എ യുടെ കൂടുതൽ വിവരങ്ങൾക്ക്: www.

-------------------------
EN: KSRTC employees strike turns chaotic
ML: കെഎസ്ആര്‍ടിസി ജീവനക്കാര്‍ പണിമുടക്കിലേക്ക്,kochi KSRTC employees strikekeralaonlinenews.com | Malayalam news, kerala news, onlinenews,

-------------------------
EN: Police cover up Nanded blast,NDTV.com.
ML: ഇംഗ്ലീഷ് വിലാസം blast,NDTV.com.

-------------------------
EN: Detailed notification in this regard is available on Ministry of Road Transport and Highways website www.morth.nic.in
ML: വിശദമായ വിജ്ഞാപനം കേന്ദ്ര റോഡ് ഗതാഗത, ഹൈവേയ് മന്ത്രാലയത്തിന്റെ വെബ്‌സൈറ്റായ www. morth. nic. in. ലഭ്യമാണ്. നിര്‍ദ്ദിഷ്ട ഭേദഗതികളിന്‍മേലുള്ള നിര്‍ദ്ദേശങ്ങളും എതിര്‍പ്പുകളും മന്ത്രാലയത്തിന് ആഗസ്റ്റ് 11 ന് മുമ്പ് ലഭ്യമാകത്തക്ക തരത്തില്‍അയച്ച് കൊടുക്കാവുന്നതാണ്.

-------------------------
EN: Volcano - climbing course that opened in 2002.
ML: Www.അനുകുടുമ്പം.com 2002-ൽ ഇറങ്ങിയ ഓ.

-------------------------
EN: For all authentic & updated information on COVID-19 related technical issues, guidelines & advisories please regularly visit: https://www.mohfw.gov.in/ and @MoHFW_INDIA .
ML: കോവിഡ് 19-മായി ബന്ധപ്പെട്ട സാങ്കേതിക വിഷയങ്ങൾ, മാര്‍ഗനിര്‍ദേശങ്ങള്‍, ഉപദേശങ്ങള്‍ എന്നിവയുടെ ആധികാരികവും പുതിയതുമായ വിവരങ്ങള്‍ക്ക് https://www. mohfw. gov. in/ അല്ലെങ്കില്‍ @MoHFW_INDIA നിരന്തരം സന്ദര്‍ശിക്കുക

-------------------------
EN: As per the regular practice, warnings are uploaded in the local website (www.imdtvm.gov.in) every day
ML: സ്ഥിരം സമ്പ്രദായ പ്രകാരം എല്ലാ ദിവസവും മുന്നറിയിപ്പുകള്‍ പ്രാദേശിക വെബ്‌സൈറ്റായ www. imdtvm. gov. in ല്‍ അപ്‌ലോഡ് ചെയ്യുകയാണ് പതിവ്.

-------------------------
EN: The results will be available on CBSEs official website cbseresults.nic.in.
ML: സിബിഎസ്ഇയുടെ ഔദ്യോഗിക വെബ്‌സൈറ്റായ cbseresults.nic.in, cbse.nic.in എന്നിവയില്‍ നിന്ന് ഫലം അറിയാം. ഇതിന് പുറമെ ഈ വര്‍ഷം മുതല്‍ google.comലും ഫലം പ്രസിദ്ധീകരിക്കും.

In [28]:
short_pairs = df.sort_values(
    "length_ratio"
).head(20)

for _, row in short_pairs.iterrows():
    print("\n-------------------------")
    print("EN:", row["src"])
    print("ML:", row["tgt"])
    print("Ratio:", row["length_ratio"])

-------------------------
EN: These are all the text jobs. The State column may be: Queued - the job is waiting and will not be spoken until its state is changed to Waiting by clicking the Resume or Restart buttons. Waiting - the job is ready to be spoken. It will be spoken when the jobs preceding it in the list have finished. Speaking - the job is speaking. The Position column shows the current sentence of the job being spoken. You may pause a speaking job by clicking the Hold button. Paused - the job is currently paused. Paused jobs prevent jobs below them from speaking. Use the Resume or Restart buttons to resume speaking the job, or click Later to move the job down in the list. Finished - the job has finished speaking. When a second job finishes, this one will be deleted. You may click Restart to repeat the job. Note: Messages, Warnings, and Screen Reader Output do not appear in this list. See the Handbook for more information.
ML: പിശകില്‍ തുടരുക
Ratio: 0.011834319526627219

-------------------------

In [29]:
long_pairs = df.sort_values(
    "length_ratio",
    ascending=False
).head(20)

for _, row in long_pairs.iterrows():
    print("\n-------------------------")
    print("EN:", row["src"])
    print("ML:", row["tgt"])
    print("Ratio:", row["length_ratio"])

-------------------------
EN: Polygala (New World Clade) Muraltia
ML: Polygala (New World Clade) Muraltia അംബോറല്ലെസീ · അക്കാന്തേസീ · അക്കാനിയേസീ · അക്കാരിയേസീ · അക്കാറ്റോകാർപേസീ · അക്കോറേസീ · അക്വിഫോളിയേസീ · അർട്ടിക്കേസീ · അഡോക്സേസീ · അതെരോസ്പേർമറ്റേസീ · അന്നോനേസീ · അനാക്കാർഡിയേസീ · അനാക്യാമ്പ്സെറോറ്റേസീ · അനാർത്രിയേസീ · അനിസോഫൈല്ലേസീ · അപ്പിയേസീ · അപ്പോഡാന്തേസീ · അപ്പോനോജെറ്റോനേസീ · അപ്പോസൈനേസീ · അഫ്ലോയിയെസീ · അഫാനോപെറ്റാലേസീ · അമരാന്തേസീ · അമരൈല്ലിഡേസീ · അരക്കേസീ · അരക്കേസീ · അരാലിയേസീ · അരിസ്റ്റലോക്കിയേസീ · അലിസ്മറ്റേസീ · അസ്പരാഗേസീ · അസ്റ്റെറോപീയേസീ · അസ്റ്റേലിയേസീ · ആക്ടിനിഡിയേസീ · ആർഗോഫൈല്ലേസീ · ആൽട്ടിഞ്ചിയേസീ · ആസ്ട്രേസീ · ആസ്ട്രോബൈലിയേസീ · ആൽസ്യൂഓസ്മിയേസീ · ആൽസ്സ്ട്രോയെമെറിയേസീ · ആൻസിസ്റ്റ്രോക്ലാഡേസീ · ഇക്സിലിറിയേസീ · ഇക്സോണാന്തേസീ · ഇറിഡേസീ · ഇലാഗ്നേസീ · ഇലിയോകാർപേസീ · ഇർവിൻഗിയേസീ · ഈക്സ്റ്റോക്സികേസീ · ഉൾമേസീ · എംബ്ലിഞ്ജിയേസീ · എക്ഡൈയോകോളിയേസീ · എബെണേസീ · എരിത്രോസൈലേസീ · എറികേസീ · എറിയോകോളേസീ · എലാറ്റിനേസീ · എസ്ക്കലോണിയേസീ · ഐക്കാസിനേസീ · ഐറ്റേസീ · ഐസോയേസീ · ഒക്നേസീ · ഒനാഗ്രേസീ · ഒപ്പിലിയേസീ · ഒലാകേസീ · ഒലിയേസീ · ഓർക്കിഡേസീ · ഓക്സാലിഡേസീ · ഓൺകോന്തിക്കേസീ · ഓറോബങ്കേസീ · കുക്കുർബിറ്റേസീ · കുർടീസിയേസീ · കുണോണിയെസീ · കന്നാബേസീ · കന്നേസീ · കനലേസീ · കപ്പാരേസീ · കമ്പാനുലേസീ · ക്യാമ്പിനേമറ്റേസീ · ക്രാമേറിയേസീ · ക്രാസ്സുലേസീ · ക്രൈസോബലനേസീ · ക്രോസ്സോസോമറ്റേസീ · ക്ലൂസിയേസീ · ക്ലിയോമാനേസീ · ക്ലീത്രേസീ · കലോഫില്ലേസീ · ക്ലോറാന്തേസീ · ക്വില്ലാജേസീ · കാക്ടേസീ · കാർഡിയോപ്ടെറിഡേസീ · കാപ്രിഫോളിയെസീ · കാബോംബേസീ · കാര്യോകരക്കേസീ · കാര്യോഫില്ലേസീ · കാരിക്കേസീ · കാർലമാന്നിയേസീ · കാൽലിക്കാന്തേസീ · കാലിസെറേസീ · കാസുവാറിനേസീ · കാൽസിയോലാറിയേസീ · കിർക്കിയേസീ · കൊൾക്കിക്കേസീ · കൊർണേസീ · കൊന്നാരേസി · കൊമ്മേലിനേസീ · കൊറിനോകാർപേസീ · കൊറിയാറിയേസീ · കൊളുമെല്ലിയേസീ · കൊൺവുൾവുലേസീ · കോംബ്രെട്ടേസീ · കോബെർലീനിയേസീ · കോസ്റ്റേസീ · കോർസിയേസീ · ഗൂഡേനിയേസീ · ഗണ്ണറേസീ · ഗ്രബ്ബിയേസീ · ഗ്രൊസ്സുല്ലാറിയേസീ · ഗാരിയേസീ · ഗിസെക്കിയേസീ · ഗൈറോസ്റ്റമോണേസീ · ഗൈസ്സൊലോമറ്റേസീ · ഗൊമൊർട്ടേഗേസീ · ഗൗപിയേസീ · ഗൗമാറ്റലേസീ · ജുൻകാജിനെസീ · ജുൻകേസീ · ജുൻഗ്ലാൻഡേസീ · ജെറാർഡിനേസീ · ജെറാനിയേസീ · ജെൻഷ്യാനേസീ · ജെസ്നേറിയേസീ · ജെൽസേമിയേസീ · ജോയിൻവില്ലിയേസീ · ടപ്പീസിയേസീ · ട്രിഗോണിയേസീ · ട്്രിമേനിയേസീ · ട്രിയൂറിഡേസീ · ട്രോക്കോഡെൻഡ്രേസീ · ട്രോപ്പിയോലേസീ · ടിക്കോഡെൻഡ്രേസീ · ടെക്കോഫൈല്ലേസീ · ടെട്രാമീലിയേസീ · ടെറ്റ്രാക്കോൻഡ്രേസീ · ടെറ്റ്രാമെരിസ്റ്റേസീ · ടൈഫേസീ · ടൊവാരിയേസീ · ടോറിസെല്ലിയേസീ · ഡയസ്കൊറിയേസീ · ഡയാപെൻസിയേസീ · ഡ്രോസറേസീ · ഡ്രോസോഫൈല്ലേസീ · ഡാഫ്നിഫൈല്ലേസീ · ഡാറ്റിസ്കേസീ · ഡാസിപൊഗോണേസീ · ഡികാപെറ്റാലേസീ · ഡിജെനെറിയേസീ · ഡിഡിയേറിയേസീ · ഡിപ്റ്റെറോകാർപേസീ · ഡിപെന്റോഡൊണ്ടേസീ · ഡിയോങ്കോഫൈല്ലേസീ · ഡിറാക്മേസീ · ഡില്ലേനിയേസീ · ഡൊര്യാന്തേസീ · തുർണിയേസീ · തീയേസീ · തൈമേലേസീ · തോമാണ്ടെർസിയേസി · ന്യൂറാഡേസീ · നാർത്തേസിയേസീ · നിംഫേസീ · നിക്ടാജിനേസീ · നിത്രാരിയേസീ · നെപന്തേസീ · നെലുമ്പോനേസീ · നോതോഫാഗേസീ · പൻഡാനേസീ · പുത്രൻജീവേസീ · പപ്പാവറേസീ · പ്രിമുലേസീ · പ്രോട്ടിയേസീ · പ്ലുംബാജിനേസീ · പ്ലാന്റാജിയേസീ · പ്ലാറ്റാനേസീ · പ്ലോകോസ്പെർമറ്റേസീ · പാൻഡേസീ · പാരാക്രിഫിയേസീ · പാസിഫ്ലോറേസീ · പിക്രാംനിയേസീ · പിക്രോഡെൻഡ്രേസീ · പിയോണിയേസീ · പിറ്റോസ്ഫോറേസീ · പീനായേയേസീ · പെട്രോസാവിയേസീ · പെഡാലിയേസീ · പെന്തോറാസീ · പെന്നാന്റിയേസീ · പെന്റാഡിപ്ലാൻഡ്രേസീ · പെന്റാഫ്രാഗ്മറ്റേസീ · പെന്റാഫ്ൈലേസീ · പെരിഡിസ്കേസീ · പെരേസീ · പെറ്റെനായിയേസീ · പെറ്റേർമാനിയേസീ · പൈപരേസീ · പൊട്ടോമോജെറ്റോണേസീ · പൊവേസീ · പൊസിഡോണിയേസീ · പോർട്ടുലാക്കേസീ · പോഡോസ്റ്റെമേസീ · പോണ്ടിഡെറിയേസീ · പോളിഗാലേസീ · പോളിഗോണേസീ · പോളിമോണിയേസീ · പൗലോണിയേസീ · ഫ്രാങ്കേനിയേസീ · ഫ്രൈമേസീ · ഫ്ലൂക്കോർഷിയേസീ · ഫ്ലജല്ലാറിയേസീ · ഫാഗേസീ · ഫിലിഡ്രേസീ · ഫിലേസിയേസീ · ഫെല്ലിനേസീ · ഫൈറ്റോലാക്കേസീ · ഫൈല്ലാന്തേസീ · ഫൈലോനോമേസീ · ഫൈസിനേസീ · ഫൗക്വിയെറിയേസീ · ബക്സേസീ · ബുടോമേസീ · ബർബ്യൂയിയേസീ · ബർബ്ിയേസീ · ബർമ്മാനിയേസീ · ബ്രുണിയേസീ · ബ്രുണേലിയേസീ · ബ്രാസ്സിക്കേസീ · ബ്രൊമേലിയേസീ · ബറ്റേസീ · ബ്ലാൻഡ്ഫോർഡിയേസീ · ബലാനോപേസീ · ബലാനോഫോറേസീ · ബർസറേസീ · ബൾസാമിനേസീ · ബസാല്ലേസീ · ബിക്സേസീ · ബിഗ്നോണിയെസീ · ബിഗോണിയേസീ · ബീബെർസ്റ്റെയ്നിയേസീ · ബെർബെറിഡേസീ · ബെർബെറിഡോപ്സിഡേസീ · ബെറ്റുലേസീ · ബൈബ്ലിഡേസീ · ബ്ൊന്നേറ്റിയേസീ · ബൊര്യേസീ · ബൊറാജിനേസീ · മഗ്നോളിയേസീ · മുണ്ടിഞ്ചിയേസീ · മ്യൂസേസീ · മയാസേസീ · മ്യോഡോകാർപേസീ · മരാന്റേസീ · മാർക്ഗ്രാവിയേസീ · മാർട്ടിന്നിയേസീ · മാല്പീജിയേസീ · മാൽവേസീ · മിട്രാസ്റ്റെമോണേസീ · മിർടേസീ · മിരിസ്റ്റിക്കേസീ · മിറികേസീ · മിസോഡെൻഡ്രേസീ · മീലിയേസീ · മെന്യാന്തേസീ · മെനിസ്പെർമേസീ · മെറ്റെന്യൂസേസീ · മെലസ്റ്റോമറ്റേസീ · മെലാന്തിയേസീ · മെലിയാന്തേസീ · മൈറോതമ്നേസീ · മൊണ്ടിയേസീ · മൊണ്ടീനിയേസീ · മൊനിമിയേസീ · മൊരീങ്ങേസീ · മൊറേസീ · മൊള്ളൂജിനേസീ · യൂക്കോമ്മിയേസീ · യൂപ്റ്റലേസീ · യൂപോമറ്റിയേസീ · യൂഫ്രോണിയേസീ · യൂഫോർബിയേസി · റൂട്ടേസീ · റപ്പറ്റിയേസീ · റുപ്പിയേസീ · റഫ്ലീസിയേസീ · റബ്ഡോഡെൻഡ്രേസീ · റൂബിയേസീ · റ്റമാരിക്കേസീ · റ്റാലിനേസീ · റ്റെനൊലോഫോനേസീ · റ്റോഫീൽഡിയേസീ · റാംനേസീ · റാണുങ്കുലേസീ · റിപൊഗോണേസീ · റെസ്റ്റിയോണേസീ · റെസിഡേസീ · റൈസോഫോറേസീ · റോറിഡുലേസീ · റോസേസീ · റൗസ്സിയേസീ · ലക്ടോറിഡേസീ · ലനാറിയേസീ · ലാർഡിസബാലേസീ · ലാമിയേസീ · ലാസിസ്റ്റമറ്റേസീ · ലിംനാന്തേസീ · ലിൻഡേർണിയേസീ · ലിത്രേസീ · ലിനേസീ · ലിമിയേസീ · ലിലിയേസീ · ലെഗുമിനേസീ · ലെന്റിബുലാറിയേസീ · ലെപിഡോബോട്രിയേസീ · ലെസിതിഡേസീ · ലൊഗാനിയേസീ · ലൊറാന്തേസീ · ലോഫിയോകാർപേസീ · ലോഫോപൈക്സിഡേസീ · ലോറേസീ · ലോവിയേസീ · ലോസേസീ · വയലേസീ · വാഹ്ലിയേസീ · വിന്ററേസീ · വിറ്റേസീ · വിവിയാനിയേസീ · വെർബനേസീ · വെല്ലോസിയേസീ · വൊക്കീസിയേസീ · ഷ്കോഫിയേസീ · ഷ്യൂസേറിയേസീ · ഷ്ലീഗേലിയേസീ · സർക്കോലീനേസീ · സ്ക്രോഫുല്ലാരേസീ · സ്കിസാന്ദ്രേസീ · സർകോബാറ്റേസീ · സ്ട്രോസ്ബർജേറിയേസീ · സന്റാലേസീ · സപ്പോട്ടേസീ · സ്ഫീനോക്ലിയേസീ · സ്ഫീറോസെപാലേസീ · സ്മൈലാക്കേസീ · സ്റ്റാച്യൂറേസീ · സ്റ്റാഫൈലിയേസീ · സ്റ്റിൽബേസീ · സ്റ്റിമോണുറേസീ · സ്റ്റിമോണേസീ · സ്റ്റെഗ്നോസ്പെർമറ്റേസീ · സ്റ്റെർലിറ്റ്സിയേസീ · സ്റ്റൈറാകേസീ · സ്റ്റൈലിഡിയേസീ · സറാസെനിയേസീ · സുറിയാനേസീ · സ്ലാഡേനിയേസീ · സാക്സിഫ്രാഗേസീ · സാന്തോർഹോയേസീ · സാപ്പിൻഡേസീ · സാബിയേസീ · സാലിക്കേസി · സാൽവഡോറേസീ · സിർക്കാസ്ട്രേസീ · സിഞ്ചിബെറേസീ · സിപ്പാരുന്നേസീ · സിമ്പ്ലോക്കേസീ · സിമ്മൊണ്ഡ്സിയേസീ · സിമരൂബേസി · സിറില്ലേസീ · സിസ്റ്റേസീ · സെൻട്രോപ്ലാക്കേസീ · സെൻട്രോലെപിഡേസീ · സെഫാലോറ്റേസീ · സെരാറ്റോഫൈല്ലേസീ · സെരോനിമറ്റേസീ · സെറ്റ്കല്ലാന്തേസീ · സെലാസ്ട്രേസീ · സെർസിഡിഫൈല്ലേസീ · സൈക്ലാന്തേസീ · സൈഗോഫൈല്ലേസി · സൈനോമോറിയേസീ · സൈപറേസീ · സൈമോഡോസേസീ · സൈറ്റിനേസീ · സൈറിഡേസീ · സൊളാനേസീ · സോസ്റ്ററേസീ · സൗറുറേസീ · ഹപ്റ്റാന്തേസീ · ഹമാമെലിഡേസീ · ഹുമിറിയേസീ · ഹലോരാഗേസീ · ഹുവാസേസീ · ഹാൻഗുവാനേസീ · ഹാലോഫൈറ്റേസീ · ഹിഡ്നോറേസീ · ഹിമാൻറ്റാൻഡ്രേസീ · ഹീമൊഡോരേസീ · ഹെർനാൻഡിയേസീ · ഹെലിക്കോണിയേസീ · ഹെൽവിഞ്ചിയേസീ · ഹൈഡ്രാഞ്ചിയേസീ · ഹൈഡ്്രോചാരിറ്റേസീ · ഹൈഡ്രോലിയേസീ · ഹൈഡ്രോസ്റ്റാക്കിയേസീ · ഹൈഡറ്റലേസീ · ഹൈപ്പോക്സിഡേസീ · ഹൈപെരിക്കേസീ ·
Ratio: 165.8

-------------------------
EN: Genera include: Libellago lineata, male Platycypha caligata Platycypha fitzsimonsi
ML: Genera include: Libellago lineata, male Platycypha caligata Platycypha fitzsimonsi കാട്ടു വിരിച്ചിറകൻ · കാട്ടു ചേരാച്ചിറകൻ · പച്ച ചേരാച്ചിറകൻ · പച്ചവരയൻ ചേരാച്ചിറകൻ · കരിവരയൻ ചേരാച്ചിറകൻ · നീലക്കണ്ണി ചേരാച്ചിറകൻ · തവിടൻ ചേരാചിറകൻ · മലബാർ ചേരാച്ചിറകൻ · പുള്ളി വിരിച്ചിറകൻ · കുങ്കുമ നിഴൽത്തുമ്പി · കൊമ്പൻ നിഴൽത്തുമ്പി · ആനമല നിഴൽത്തുമ്പി · പുള്ളി നിഴൽത്തുമ്പി · ചെറു നിഴൽത്തുമ്പി · പർവ്വതവാസി നിഴൽത്തുമ്പി · പൊന്മുടി നിഴൽത്തുമ്പി · ചെമ്പൻ നിഴൽത്തുമ്പി · പീലിത്തുമ്പി · ചുട്ടിച്ചിറകൻ തണൽത്തുമ്പി · ചെറിയ തണൽതുമ്പി · കാട്ടു തണൽതുമ്പി · മേഘവർണ്ണൻ · തവളക്കണ്ണൻ (തുമ്പി) · നീർമാണിക്യൻ · കരിമ്പൻ അരുവിയൻ · തെക്കൻ അരുവിയൻ · വടക്കൻ അരുവിയൻ · ചെങ്കറുപ്പൻ അരുവിയൻ · മഞ്ഞക്കാലി പാൽത്തുമ്പി · ചെങ്കാലി പാൽത്തുമ്പി · കാട്ടുമുളവാലൻ · മലബാർ മുളവാലൻ · വയനാടൻ മുളവാലൻ · ചുട്ടിച്ചിറകൻ മുളവാലൻ · കരിം ചിറകൻ മുളവാലൻ · ചെങ്കറുപ്പൻ മുളവാലൻ · മഞ്ഞക്കറുപ്പൻ മുളവാലൻ · പഴനി മുളവാലൻ · നീലഗിരി മുളവാലൻ · വടക്കൻ മുളവാലൻ · തെക്കൻ മുളവാലൻ · എണ്ണക്കറുപ്പൻ · ചതുപ്പു മുളവാലൻ · കരിഞ്ചെമ്പൻ മുളവാലൻ · നീലച്ചിന്നൻ · നീലച്ചുട്ടി · പത്തി പുൽചിന്നൻ · വെള്ളപ്പുൽ ചിന്നൻ · നാട്ടു പുൽചിന്നൻ · കാട്ടു പുൽചിന്നൻ · ചെറുനീലിത്തുമ്പി · അരുവിത്തുമ്പി · കനൽവാലൻ ചതുപ്പൻ · നാട്ടുചതുപ്പൻ · കരിംപച്ച ചതുപ്പൻ · തീച്ചതുപ്പൻ · മഞ്ഞപ്പുൽ മാണിക്യൻ · നീല പുൽമാണിക്യൻ · കരിയിലത്തുമ്പി · ചുട്ടിവാലൻ താമരത്തുമ്പി · മലയൻ താമരത്തുമ്പി · ഇളനീലി പൂത്താലി · മഞ്ഞ വരയൻ പൂത്താലി · കാട്ടുപൂത്താലി · നാട്ടുപൂത്താലി · കുറുവാലൻ പൂത്താലി · ചെമ്മുഖപ്പൂത്താലി · തുരുമ്പൻ രാജൻ · മരതക രാജൻ · നീലരാജൻ (തുമ്പി) · തവിട്ട്‍ രാജൻ · തത്തമ്മത്തുമ്പി · സൂചിവാലൻ രാക്കൊതിച്ചി · തുരുമ്പൻ ചാത്തൻ · പൊക്കൻ കടുവ · ചതുരവാലൻ കടുവ · സൈരന്ധ്രിക്കടുവ · പുഴക്കടുവ · പുള്ളിവാലൻ ചോലക്കടുവ · കൊമ്പൻ ക‌‌‌ടുവ തുമ്പി · നാട്ടുകടുവ · പെരുവാലൻ കടുവ · കടുവാച്ചിന്നൻ · നീലഗിരി നഖവാലൻ · ചൂണ്ടവാലൻ കടുവ · വയനാടൻ കടുവ · കുറു നഖവാലൻ · നീലഗിരി മലമുത്തൻ · കാട്ടു മരതകൻ · പുള്ളി നീർക്കാവലൻ · നാട്ടു നീർക്കാവലൻ · കാട്ടു പെരുംകണ്ണൻ · അടിപിടിയൻ പെരുംകണ്ണൻ · ആറ്റു പെരുംകണ്ണൻ · മഞ്ഞ പെരുംകണ്ണൻ · കാനന പെരുംകണ്ണൻ · ഇന്ത്യൻ പെരുംകണ്ണൻ · ചൂടൻ പെരുംകണ്ണൻ · മകുടിവാലൻ തുമ്പി · ചോപ്പൻ കുറുവാലൻ · ചങ്ങാതിത്തുമ്പി · മതിൽത്തുമ്പി · കാട്ടുപതുങ്ങൻ · വയൽത്തുമ്പി · കരിനിലത്തൻ · ചുട്ടിനിലത്തൻ · നാട്ടുനിലത്തൻ · തീക്കറുപ്പൻ · പാണ്ടൻ പരുന്തൻ · നീല നീർത്തോഴൻ · കരിമ്പൻ ചരൽമുത്തി · ചോരവാലൻ തുമ്പി · കുള്ളൻ വർണ്ണത്തുമ്പി · മഞ്ഞവരയൻ വർണ്ണത്തുമ്പി · പൊഴിത്തുമ്പി · തവിടൻ തുരുമ്പൻ · പുൽ തുരുമ്പൻ · സ്വാമിത്തുമ്പി · കാട്ടുപുള്ളൻ · ചെന്തവിടൻ വ്യാളി · നീല വ്യാളി · ത്രിവർണ്ണൻ വ്യാളി · പവിഴവാലൻ വ്യാളി · പച്ച വ്യാളി · ചെറു വ്യാളി · നീല കറുപ്പൻ വ്യാളി · നീല കുറുവാലൻ · ഓണത്തുമ്പി · പുള്ളിവാലൻ തുമ്പി · തവിട്ടുവെണ്ണിറാൻ · ചെറു വെണ്ണീറൻ · കരിനീലച്ചിറകൻ · തുലാത്തുമ്പി · കുങ്കുമച്ചിറകൻ · കുള്ളൻ തുമ്പി · പവിഴവാലൻ · ചെംമ്പൻ പരുന്തൻ · കരിംമ്പൻ പരുന്തൻ · സിന്ദൂരത്തുമ്പി · കാർത്തുമ്പി · ചോപ്പൻ പാറമുത്തി · ചെമ്പൻ തുമ്പി · കാറ്റാടിത്തുമ്പി · തീക്കരിമുത്തൻ · നീരോട്ടക്കാരൻ · സൂചിവാലൻ സന്ധ്യത്തുമ്പി · നീലഗിരിക്കോമരം · മിനാരക്കോമരം · ഗോവൻ കോമരം · ചിന്നൻ കോമരം · കൊമ്പൻ കോമരം · കാവിക്കോമരം · തെക്കൻ കോമരം · നിഴൽ കോമരം ·
Ratio: 47.77777777777778

-------------------------
EN: Making decisions.
ML: തീരു ​ മാ ​ ന ​ ങ്ങ ​ ളെ ​ ടു ​ ക്കു ​ മ്പോൾ: പ്രധാ ​ ന ​ പ്പെട്ട കാര്യ ​ ങ്ങ ​ ളിൽ തീരു ​ മാ ​ ന ​ മെ ​ ടു ​ ക്കു ​ മ്പോൾ ദൈവ ​ ത്തി ​ ന്‍റെ വചനത്തി ​ ന്‍റെ ​ യും സംഘട ​ ന ​ യു ​ ടെ ​ യും സഹായം തേടി ​ ക്കൊണ്ട് നമുക്കു ദൈവ ​ ത്തോ ​ ടുള്ള വിശ്വ ​ സ്‌തത കാണി ​ ക്കാ ​ നാ ​ കും.
Ratio: 38.5

-------------------------
EN: Week 4
ML: 4 -‍ാ‍ം വാരം ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․ ․
Ratio: 26.5

-------------------------
EN: is outstanding!
ML: ( ഇംഗ്ലീഷ്‌) എന്ന വീഡി ​ യോ കാണി ​ ച്ച ​ പ്പോ ​ ഴുള്ള വിദ്യാർഥി ​ ക ​ ളു ​ ടെ പ്രതി ​ ക ​ രണം അതിശ ​ യി ​ പ്പി ​ ക്കു ​ ന്ന ​ താ ​ യി ​ രു ​ ന്നു.
Ratio: 21.0

-------------------------
EN: Face facts.
ML: നിങ്ങൾ ചെയ്‌ത ​ തി ​ ന്‍റെ ഉത്തരവാ ​ ദി ​ ത്വം ഏറ്റെടു ​ ക്കുക, ഇണയ്‌ക്ക് അനുഭ ​ വ ​ പ്പെ ​ ടുന്ന വേദന മനസ്സി ​ ലാ ​ ക്കുക, അതിന്‌ തക്ക കാരണ ​ മി ​ ല്ലെന്ന് തോന്നു ​ ന്നെ ​ ങ്കിൽപ്പോ ​ ലും.
Ratio: 21.0

-------------------------
EN: Grammia parthenice Giant leopard moth Hypercompe scribonia Nyctemera Arctia villica Final instar of Euchaetes egle Platyprepia virginalis, caterpillar Apantesis arge, caterpillar Halysidota tessellaris, cocoon
ML: Grammia parthenice Giant Leopard Moth, Hypercompe scribonia Magpie Moth, Nyctemera annulata Banded woolly bear, Pyrrharctia isabella Arctia villica Late instar of Milkweed tussock moth, Euchaetes egle on the UF / IFAS Featured Creatures Web site അരളി ശലഭം · ആവണച്ചോപ്പൻ · ഇരുളൻ പുൽനീലി · കടുവാവരയൻ ഇരട്ടവാലൻ · ഗരുഡശലഭം · ചക്കര ശലഭം · ചിത്രാംഗദൻ · ചെറു പുൽനീലി · ചെറുചെമ്പൻ അറബി · ചൊട്ടശലഭം · ചോരത്തുഞ്ചൻ · നീലക്കടുവ · നീലപ്പുളിയൻ · പാണലുണ്ണി · പൊട്ടില്ലാ മഞ്ഞപ്പാപ്പാത്തി · ബുദ്ധമയൂരി · മഞ്ഞനീലി · മോർമൺ · വെള്ളച്ചാത്തൻ · വെള്ളിലത്തോഴി · വെള്ളപ്പരപ്പൻ · വൻ ചെങ്കണ്ണി · സിൽവറി മെഡോ ബ്ലൂ · നരിവരയൻ · ചെറുപുലിത്തെയ്യൻ · തവിടൻ ആര · തളിർനീലി · കൃഷ്ണശലഭം · ചെറുപുള്ളിച്ചാടൻ · ചിന്നപ്പുൽനീലി · രത്നനീലി · നവാബ് · ചെമ്പഴകൻ · ഇലമുങ്ങി · ചേരാച്ചിറകൻ · സ്ലേറ്റ് ഫ്ളാഷ് · തകരമുത്തി · ചുണ്ടൻ ശലഭം · മരോട്ടിശലഭം · കാട്ടുപാത്ത · വരയൻ വാൾവാലൻ · വയങ്കതൻ · മണിമാരൻ · ചുട്ടിക്കറുപ്പൻ · മലബാർ റാവൻ · പുള്ളിവാലൻ · ചുട്ടിമയൂരി · ഭൂപടശലഭം · ഇരുതലച്ചി · ക്ലിപ്പർ · വെള്ളിവാലൻ · ചോലവിലാസിനി · വിലാസിനി · ചെങ്കണ്ണി · നാട്ടുപാത്ത · ആൽബട്രോസ് · മുളങ്കാടൻ · പൂങ്കണ്ണി · ചിത്രിത · ചെങ്കോമാളി · തീച്ചിറകൻ · പഞ്ചനേത്രി · പനങ്കുറുമ്പൻ · ലെയ്സ് ശലഭം · ക്രൂയിസർ · പുലിത്തെയ്യൻ · ജോക്കർ · ചുരുൾവാലൻ പൂമ്പാറ്റ · ചോലരാജൻ · ഓക്കിലശലഭം · നീലനീലി · നാട്ടുവേലിനീലി · വനദേവത · വൻചെങ്കണ്ണി · കുഞ്ഞുവാലൻ · ചോണൻ പൂമ്പാറ്റ · നാരക ശലഭം · നാരകക്കാളി · പൊട്ടുവാലാട്ടി · വിറവാലൻ · എരിക്കുതപ്പി · മയിക്കണ്ണി · നാട്ടുകോമാളി · മഞ്ഞത്തകരമുത്തി · കരിയില ശലഭം · നീലക്കുടുക്ക · കനിത്തോഴി · അക്കേഷ്യനീലി · നാൽക്കണ്ണി · ചെംകുറുമ്പൻ · മുളംതവിടൻ · ചിത്രകൻ · കാനനത്തോഴി · നാട്ടുറോസ് · വരയൻ കോമാളി · ഇരുളൻ കോമാളി · നീലവരയൻ കോമാളി · പൊന്തച്ചുറ്റൻ · ഇരുവരയൻ പൊന്തച്ചുറ്റൻ · ഒറ്റവരയൻ സാർജന്റ് · പേഴാളൻ · പട്ടാണി നീലി · വഴന ശലഭം · വെള്ളിവരയൻ ശലഭം · വയൽക്കോത · പുള്ളിക്കുറുമ്പൻ · നീലരാജൻ · പൊട്ടുവെള്ളാട്ടി · തെളിനീലക്കടുവ · മലബാർ മിന്നൻ · വലിയ ഓക്കിലനീലി · സുവർണ്ണ ശലഭം · ചോക്ലേറ്റ്_ശലഭം · നീലവിറവാലൻ · ഓലക്കണ്ടൻ · കറുപ്പൻ · തവിടൻ · പൂച്ചക്കണ്ണി · നാടോടി · പയനിയർ · വെള്ളപഫിൻ · പുള്ളിച്ചാത്തൻ · ശരശലഭം · സുവർണ്ണആര · വെള്ളവരയൻആര · പുള്ളിപ്പരപ്പൻ · കുഞ്ഞിപ്പരപ്പൻ · ചോക്കളേറ്റ് ആൽബട്രോസ് · അക്കാഡിയൻ ഹെയർസ്ട്രീക്ക് · പർപ്പിൾ ഹെയർസ്ട്രീക്ക് · പർപ്പിൾ എംപറർ · ജെസെ ബെൽ · കോമൺ ഗ്ലൈഡർ · വുഡ്ലാൻഡ് ഗ്രെയ്ലിങ് · സ്പെക്കിൾഡ് വുഡ് · ഹെർമിറ്റ് · അപ്പോളോ · കോമ · ഡിനാസ്റ്റർ നെപ്പോളിയൻ · റോയൽ അസീറീയൻ · മദർ ഓഫ് പേൾ · കാറ്റിൽ ഹാർട്ട് സ്വാളോടെയിൽ · ലാർജ് ബേഡ്വിങ് സ്വാളോടെയിൽ · പർപ്പിൾ സ്പോട്ടഡ് സ്വാളോടെയിൽ · മൂർലാൻഡ് ക്ലൗഡഡ് യെല്ലോ · പീഡ്മോൺട് റിങ്‍ലറ്റ് · സ്കേഴ്സ് കോപ്പർ · പീക്ക് വൈറ്റ് · ക്ലൗഡ്‍ലസ് ജയന്റ് സൾഫർ · പെരുഞ്ചിറകൻ · അറ്റ്‍ലസ് ശലഭം · തേനീച്ച ശലഭം · വെങ്കണ്ണനീലി · മൂങ്ങക്കണ്ണൻശലഭം · മരതകശലഭം · അമ്പിളിക്കണ്ണൻ · കനിതുരപ്പൻ · തലയോട്ടിശലഭം · അരളി നിശാശലഭം · സുവർണ്ണചക്രവർത്തി · ടൈഗർ · ക്ഷേത്രഗണിതജ്ഞ · പ്രേതശലഭം · തൂവൽശലഭം · ആടുശലഭം · കോഡ്ലിങ് ശലഭം · സ്ഫിങ്സ് ശലഭങ്ങൾ · ഉറാനിഡ് മോത്ത് · യുക്രോമിഡ് മോത്ത് · ബീ മോത്ത് · പെരികോപൈൻ മോത്ത് · സലൊവാൻഡ് ഉറാനിഡ് മോത്ത് · മെറ്റാലിക് മോത്ത് · സിന്റോമിഡ് മോത്ത് · ജിയോമെട്രിഡ് മോത്ത് · വേരിയബിൾ ബർനറ്റ് മോത്ത് · ഹമ്മിങ്ബേഡ് ഹാക് മോത്ത് · അഗാരിസ്റ്റിഡ് മോത്ത് · പെരികോപൈൻ മോത്ത് · ടെറോതൈസാനിഡ് മോത്ത് · ചാൾകൊസിന് മോത്ത് · ഹെപിയാലിഡ് മോത്ത് · വെർഡന്റ് ഹാക്ക് മോത്ത് · സ്വഈറ്റ് പൊട്ടറ്റോ ഹോൺവേം മോത്ത് · റോക്കറ്റ് മോത്ത് · ജമൈക്കൻ ഉറാനിഡ് മോത്ത് ·
Ratio: 20.583333333333332

-------------------------
EN: What contributed to this?
ML: അത്‌ പതു ​ ക്കെ ​ പ്പ ​ തു ​ ക്കെ ​ യുള്ള ഒരു പ്രക്രി ​ യ ​ യാ ​ യി ​ രു ​ ന്നെന്ന് വിശദീ ​ ക ​ രി ​ ച്ചു ​ കൊണ്ട് ആ പുസ്‌തകം ഇങ്ങനെ പറയുന്നു: “കൃഷി ​ യി ​ ട ​ ത്തി ​ നും മേച്ചിൽപ്പു ​ റ ​ ങ്ങൾക്കും ആയി ആളുകൾ അവി ​ ടെ ​ യുള്ള വൃക്ഷല ​ താ ​ ദി ​ കൾ സ്ഥിരം നശിപ്പി ​ ച്ചു ​ കൊ ​ ണ്ടി ​ രു ​ ന്നു.
Ratio: 19.25

-------------------------
EN: Child - rearing.
ML: കുട്ടി ​ കളെ വളർത്തു ​ മ്പോൾ: ദൈവ ​ ത്തി ​ ന്‍റെ വചനത്തി ​ നു ചേർച്ച ​ യിൽ കുട്ടി ​ കളെ പരിശീ ​ ലി ​ പ്പി ​ ച്ചു ​ കൊണ്ട് ക്രിസ്‌തീ ​ യ ​ മാ ​ താ ​ പി ​ താ ​ ക്കൾ യഹോ ​ വ ​ യോ ​ ടുള്ള വിശ്വ ​ സ്‌തത കാണി ​ ക്കു ​ ന്നു.
Ratio: 19.0

-------------------------
EN: For instance:
ML: നിങ്ങളു ​ ടെ വസ്‌തു ​ വ ​ ക ​ ക ​ ളെ ​ ല്ലാം ഒരു പ്രകൃ ​ തി ​ ദു ​ ര ​ ന്ത ​ ത്തിൽ നഷ്ടപ്പെ ​ ടു ​ ന്നെ ​ ങ്കി ​ ലോ?
Ratio: 17.5

-------------------------
EN: Certainly not!
ML: യഹോവ തന്‍റെ ജനത്തി ​ നാ ​ യി കരുതു ​ ന്നു എന്ന് ബോധ്യ ​ പ്പെ ​ ടു ​ ത്തുന്ന അനവധി വിവര ​ ണങ്ങൾ നമുക്ക് ബൈബി ​ ളിൽ വായി ​ ക്കാ ​ നാ ​ കും.
Ratio: 16.5

-------------------------
EN: You made a mistake.
ML: സംഭ ​ വി ​ ച്ചു ​ പോയ കാര്യ ​ ത്തെ ​ പ്രതി എനിക്ക് അതിയായ ദുഃ ​ ഖമു ​ ണ്ടെ ​ ന്നും അദ്ദേഹത്തിന്‍റെ ഓ ​ ഫീ ​ സിൽ തുടരാൻ എനിക്ക് യോ ​ ഗ്യത ​ യി ​ ല്ലെന്നും എന്നെ വേറെ എങ്ങോ ​ ​ ട്ടെങ്കി ​ ലും മാ ​ റ്റണ ​ മെന്നും കാണി ​ ച്ചു ​ കൊ ​ ണ്ട് ഞാൻ അ ​ ദ്ദേഹത്തി ​ ന്‌ ഒരു ചെറിയ കത്ത്‌ എഴുതി.
Ratio: 16.5

-------------------------
EN: There are a few questions to ask here.
ML: ഇവിടെ ഉയർന്നു വരുന്ന ചില ചോദ്യങ്ങളുണ്ട്. തങ്കച്ചനെ അടക്കിയതിന്റെ ഏതാനും അടി മാറി ഇടുക്കി രൂപതയിൽപെട്ട പേഴുംങ്കണ്ടം സെൻ്‌റ് ജോസഫ് കത്തോലിക്കാ പള്ളിയുടെ സെമിത്തേരിയിൽ ദളിതരല്ലാത്ത വിശ്വാസികളെ അടക്കുന്നുണ്ട്. ഈ സെമിത്തേരിക്ക് ലൈസൻസ് ഉണ്ടോയെന്നും തട്ടുപാറക്ക് മേൽഭാഗത്ത് കുന്നിൻ പ്രദേശത്ത് സ്ഥിതിചെയ്യുന്ന ഇവിടെ അടക്കുന്ന മൃതശരിരങ്ങളുടെ അവിഷിപ്തങ്ങൾ തട്ടുപാറക്കു മുകളിലൂടെ ഒഴുകിയിറങ്ങി താഴ്‌വാരങ്ങളിലെ കുടിവെള്ള സ്രോതസ്സുകളിൽ എത്തുന്നുണ്ടോയെന്നും ആരും പരിശോധിക്കാത്തതും പരിസരവാസികൾക്ക് പരാതിയില്ലാത്തതും എന്തുകൊണ്ടാണെന്ന് പരിശോധിക്കപ്പെടേണ്ടതല്ലേ. അടക്കപ്പെട്ട ഒരു മൃതശരീരം പുറത്തെടുക്കുന്നതിനാവശ്യമായ നിയമപരമായ നടപടിക്രമങ്ങൾ തങ്കച്ചന്റെ കേസ്സിൽ പാലിക്കപ്പെടാതെ പോയത് എന്തുകൊണ്ടാണ്. അടക്കിയ കുഴിക്ക് എട്ടടിയോളം താഴ്ചയുണ്ടെന്ന് സഭ പറയുമ്പോൾ ആഴം കുറവാണെങ്കിൽ ആഴം കൂട്ടിമറവുചെയ്യുന്നതിനു പകരം ബോഡിയെടുത്ത് വിദൂരതയിൽ കൊണ്ടുപോയത് എന്തിന്. കത്തോലിക്കാ പള്ളികളുടെ കല്ലറകളുടെ ആഴം ഇതിൽ കൂടുതലില്ലാത്തത് എന്തുകൊണ്ടാണ്. കട്ടപ്പന സി.എസ്സ്. ഐ പള്ളിയുടെ സെമിത്തേരി ടൗണിനു നടുവിലാണ്. സെന്റ് ജോർജ്ജ് കത്തോലിക്കാപള്ളിയുടെ സെമിത്തേരി ജനവാസകേന്ദ്രത്തിനിടയിലാണ്. തൊടുപുഴ ന്യൂമാൻ കോളേജിനുള്ളിലെ പുതിയ പള്ളിയും സെമിത്തേരിയും കാണുക. എന്തിന് ,കേരളത്തിന്റെ ഒരറ്റം മുതൽ അങ്ങേയറ്റം വരെ സഞ്ചരിച്ചാൽ പ്രമുഖമായ ക്രിസ്തീയ സഭകളുടെ സെമിത്തേരികൾക്ക് ഭൂരിഭാഗവുംആവശ്യമായ അംഗീകാരങ്ങൾ ഇല്ലെന്നും ജനവാസകേന്ദ്രത്തിന് നടുവിലോ സമീവത്തോ ആണെന്നുംകാണാം .എന്തുകൊണ്ടാണ് ഭരണകൂടം ഇവയുടെ മേൽ നടപടികൾ സ്വികരിക്കാത്തത് .
Ratio: 15.5

-------------------------
EN: Kunjathbail-Mangaladevi, State Bank-Thanneerubavi, State Bank-Chelyaru-MRPL, Mangalore(AB Shetty Circle)-Amblamogaru routes.
ML: അമ്പാർ -ചെറുഗോളി റോഡ് (മംഗൽപാടി പഞ്ചായത്ത്), ബദ്രിയ നഗർ അംഗൻവാടി ബോൾക്കുന്ന് റോഡ് (കുമ്പള പഞ്ചായത്ത്), ബങ്കര മഞ്ചേശ്വരം -കാടിയാർ റോഡ് (മഞ്ചേശ്വരം പഞ്ചായത്ത്), മുണ്ടിത്തടുക്ക സ്കൂൾ റോഡ് (എൻമകജെ പഞ്ചായത്ത്), പർളാഡം മദ്​റസ സൈഡ് റോഡ് (പുത്തിഗെ പഞ്ചായത്ത്), കുണ്ടച്ചകട്ടെ -സാൻതിയോട് റോഡ് (പൈവളിഗെ പഞ്ചായത്ത്), നീരോളിക-കൊണില റോഡ് (മീഞ്ച പഞ്ചായത്ത്), ആനക്കല്ല് -കത്തരക്കോടി റോഡ് (വോർക്കാടി പഞ്ചായത്ത്), ഹിദായത്ത് നഗർ -മദക്കം റോഡ് (മംഗൽപാടി പഞ്ചായത്ത്), സി. എച്ച്. സി മാട്ടംകുഴി റോഡ് (കുമ്പള പഞ്ചായത്ത്), ചെക്പോസ്​റ്റ്​ -കടവു റോഡ് (മഞ്ചേശ്വരം പഞ്ചായത്ത്), ഷേണി -ചർച്ച് റോഡ് (എൻമകജെ പഞ്ചായത്ത്), മണിയമ്പാറ -കാന്തലായം റോഡ് (പുത്തിഗെ പഞ്ചായത്ത്), മേർക്കള്ള മസ്ജിദ് റോഡ് (പൈവളിഗെ പഞ്ചായത്ത്), ലക്ഷംവീട്-മിയാപ്പദവ് റോഡ് (മീഞ്ച പഞ്ചായത്ത്), ഗുഅഡപ്പടുപ്പ്- പിലിചാമുണ്ഡി റോഡ് (വോർക്കാടി പഞ്ചായത്ത്), കണ്ണാടിക്കാനം-കുദുവ റോഡ് (എൻമകജെ പഞ്ചായത്ത്), പുത്തിഗെ ജുമാമസ്ജിദ് റോഡ് (പുത്തിഗെ പഞ്ചായത്ത്), പാത്തൂർ -മാടൂർ റോഡ് (വൊർക്കാടി പഞ്ചായത്ത്), നാട്ടക്കല്ല് -മാട്ടെ റോഡ് (മീഞ്ച പഞ്ചായത്ത്), അടുക്ക-കുനിൽ സ്കൂൾ റോഡ് (മംഗൽപാടി പഞ്ചായത്ത്), അംബേദ്കർ -ഡോൺ ബോസ്കോ സ്കൂൾ റോഡ് (മഞ്ചേശ്വരം പഞ്ചായത്ത്), ഉക്കിനടുക്ക- പർപ്പക്കരിയ റോഡ് (എൻമകജെ പഞ്ചായത്ത്), മംഗലടുക്ക-ദഡ്പന-സിഗെമൂല റോഡ് (പുത്തിഗെ പഞ്ചായത്ത്), ദൈഗോളി-ബോർക്കള റോഡ് (വൊർക്കാടി പഞ്ചായത്ത്) എന്നീ റോഡുകളുടെ പുനരുദ്ധാരണത്തിന്​ അഞ്ചുലക്ഷം രൂപ വീതമാണ്​ അനുവദിച്ചത്.
Ratio: 15.11111111111111

-------------------------
EN: His point?
ML: പണത്തെ ​ ക്കു ​ റി ​ ച്ചു ​ ള്ള ഉത്‌കണ്‌ഠ: ‘ ദാരി ​ ദ്ര്യ ​ വും സമ്പത്തും എനിക്കു തരരുതേ ’ എന്ന് ജ്ഞാനി ​ യായ ഒരു മനുഷ്യൻ ഒരിക്കൽ പ്രാർഥി ​ ച്ചു.
Ratio: 15.0

-------------------------
EN: Are such notions correct?
ML: മറ്റു ചിലരാ ​ കട്ടെ തങ്ങളുടെ കുടും ​ ബ ​ പ ​ ശ്ചാ ​ ത്തലം, ഒരു മോശ ​ മായ ജീവിതം നയിക്കു ​ ന്ന ​ തി ​ നോ മാതാ ​ പി ​ താ ​ ക്ക ​ ളു ​ ടെ തെറ്റുകൾ ആവർത്തി ​ ക്കു ​ ന്ന ​ തി ​ നോ ഉള്ള കാരണ ​ മാ ​ ണെന്ന് വിചാ ​ രി ​ ക്കു ​ ന്നു.
Ratio: 15.0

-------------------------
EN: I could not believe my eyes.
ML: എനിക്കെന്റെ കണ്ണുകളെ വിശ്വസിക്കാനായില്ല .ദേഹത്ത് ഇറുകി കിടക്കുന്ന കഴുത്ത് ഇറക്കി വെട്ടിയ വെള്ള നിറത്തിലുള്ള ഒരു ടോപ്പും ജീൻസിന്റെ തുണി കൊണ്ട് തയ്ച്ച മുട്ടിനു തൊട്ട് താഴെ വരെയെത്തുന്ന ഒരു കേപിയുമാണിപ്പോഴത്തെ അവളുടെ വേഷം ടോപ്പിനടിയിൽ ബ്രാ ധരിച്ചിട്ടില്ലെന്ന് ഒറ്റ നോട്ടത്തിൽ തന്നെ ആർക്കും മനസ്സിലാക്കാം തുടുത്തു കൊഴുത്ത മുലകൾ അതിനുള്ളിൽ തിങ്ങി നിറഞ്ഞ് കഴുത്തിനു പുറത്തേക്ക് തള്ളി നിൽക്കുകയാണ് . തിണർത്ത് നിൽക്കുന്ന മുല ഞട്ടുകൾ ടോപ്പിനെ തുളച്ച പുറത്തേക്ക് വരാൻ തയ്യാറായി നിൽക്കുന്നു . ഇറുക്കമുള്ള ടോപ്പായതിനാൽ അവളുടെ മിനുസമുള്ള വയറും പൊക്കിൾ ചുഴിയുമൊക്കെ ഭംഗിയായി കാണാനാവുന്നുണ്ട് കേപ്രിയാണെങ്കിൽ അവളുടെ സമൃദ്ധമായ കുണ്ടിക്കുന്നുകളുടെ വടിവ് വ്യക്ടമാക്കുന്നു മുൻ വശത്ത് നിന്ന് നോക്കിയാൽ അവളുടെ പൂറിന്റെ ആകൃതി പോലും വൃക്ടമായി മനസ്സിലാക്കാൻ കഴിയും . ഈ കാമോദ്ദീപകമായ കാഴ്ച കണ്ടയുടനെ ഞാൻ കമ്പിയടിച്ച നിലയിലായി
Ratio: 14.833333333333334

-------------------------
EN: Rajagopal, MLA, presided.
ML: ഒ. രാജഗോപാല്‍ എംഎല്‍എ അധ്യക്ഷത വഹിച്ചു. വിവേകാന്ദ വേദിക് മിഷന്‍ അധ്യക്ഷ ഡോ.എം. ലക്ഷ്മികുമാരി, സുരേഷ് ഗോപി എംപി, ശ്രീരാമകൃഷ്ണമഠം അധ്യക്ഷന്‍ സ്വാമി. സദ്ഭാവനാനന്ദ, കെപിഎംഎസ് അധ്യക്ഷന്‍ നീലകണ്ഠന്‍ മാസ്റ്റര്‍ ശാന്തിഗിരി ആശ്രമം ജനറല്‍ സെക്രട്ടറി സ്വാമി ഗുരുരത്നം ജ്ഞാനതപസ്വി, കവി പി. നാരായണക്കുറുപ്പ്, വിചാരകേന്ദ്രം അധ്യക്ഷന്‍ ഡോ.എം. മോഹന്‍ദാസ്. ജനറല്‍ സെക്രട്ടറി കെ.സി. സുധീര്‍ ബാബു എന്നിവര്‍ സംസാരിച്ചു.
Ratio: 14.333333333333334

-------------------------
EN: What did he mean?

In [30]:
df["src_chars"] = df["src"].str.len()
df["tgt_chars"] = df["tgt"].str.len()

print(
    df[["src_chars", "tgt_chars"]].describe()
)

          src_chars     tgt_chars
count  1.481107e+06  1.481107e+06
mean   5.890681e+01  6.723218e+01
std    5.435774e+01  5.646733e+01
min    5.000000e+00  5.000000e+00
25%    2.600000e+01  3.300000e+01
50%    4.300000e+01  5.200000e+01
75%    7.400000e+01  8.300000e+01
max    2.019300e+04  6.100000e+03

In [31]:
short_src = df[df["src_words"] <= 3]

print("Source sentences with <=3 words:", len(short_src))

for _, row in short_src.head(20).iterrows():
    print("\nEN:", row["src"])
    print("ML:", row["tgt"])

Source sentences with <=3 words: 187429

EN: what has happened?
ML: എന്താണു സംഭവം?

EN: They didn't talk.
ML: അവര് മിണ്ടിയിട്ടില്ല.

EN: Well, anything!
ML: ആ, എന്തേലും ആവട്ട്‌ !

EN: I can go
ML: എനിക്ക് കഴിയും

EN: Parish priest Fr.
ML: മേരീസ് ഇടവകാംഗമായ ഫാ.

EN: But India won.
ML: പക്ഷേ, ഇന്ത്യ ജയിച്ചു.

EN: says Mayawati
ML: """ മായാവതി പറയുന്നു"

EN: What's up
ML: ങ്ങാ എന്താടി….

EN: Consider these.
ML: ശ്രദ്ധിക്കാം ഈ കാര്യങ്ങള്‍.

EN: Win for India
ML: ഇന്ത്യക്കായി നേടിയത്

EN: They shot him.
ML: അവർ അവനെ വെടിവെച്ചുകൊന്നു.

EN: Wonderful, wonderful technology
ML: അത്ഭുതകരമായ സാങ്കേതികവിദ്യ

EN: Dont forget that.
ML: എന്ന കാര്യം വിസ്മരിക്കരുത്.

EN: Trains partially cancelled
ML: പാസ്സഞ്ചര്‍ ട്രെയിനുകള്‍ ഭാഗികമായി റദ്ദു ചെയ്തു

EN: Chances of victory
ML: വിജയിക്കുന്നു സാധ്യത

EN: _Add Files
ML: ഫയലുകള്‍ ചേര്‍ക്കുക

EN: for release
ML: മോചനത്തിനായി

EN: Vintage cars
ML: വിന്റേജ് കാറുകൾ

EN: This contentious battle
ML: ഇക്കുറി പൊരിഞ്ഞ പോരാട്ടമാ .

EN: Not illegal.
ML: അല്ലാതെ നിയമവിരുദ്ധമായല്ല.

In [32]:
# Candidate quality filters

valid_basic = (
    df["src"].notna() &
    df["tgt"].notna() &
    (df["src"].str.strip() != "") &
    (df["tgt"].str.strip() != "")
)

no_web_noise = ~df["possible_web_noise"]

reasonable_length = (
    (df["src_words"] <= 100) &
    (df["tgt_words"] <= 100)
)

reasonable_ratio = (
    (df["length_ratio"] >= 0.2) &
    (df["length_ratio"] <= 3.0)
)

reasonable_malayalam = df["latin_ratio"] <= 0.50

candidate = (
    valid_basic &
    no_web_noise &
    reasonable_length &
    reasonable_ratio &
    reasonable_malayalam
)

print("Original:", len(df))
print("After candidate filtering:", candidate.sum())
print("Removed:", (~candidate).sum())
print("Retention:", round(candidate.mean() * 100, 2), "%")

Original: 1481107
After candidate filtering: 1471729
Removed: 9378
Retention: 99.37 %